#!/usr/bin/env node
// Generate the deterministic half of the code from the system IR.
//
//   node tools/codegen.mjs <system-dir> [--out generated/<System>]
//
// The split matters. Anything mechanically derivable from the model belongs in a SCRIPT: it is
// total, idempotent, and its diff is how a model change gets reviewed. Anything needing judgement —
// the body of a business rule, the arithmetic behind a derived field, the example data a test needs
// — belongs to the `codegen` skill, which reads reference/llms/ and fills the marked holes.
//
// So this emits: the solution, both projects, Program.cs, every event record, every aggregate's
// Create/Apply skeleton, every view type, every validator for a periphery rule, the Alba harness,
// and one test per GWT. It emits NO business logic, and says so at every hole with TODO(codegen).
//
// API shapes here are taken from reference/llms/, never from memory:
//   [WolverinePost] + [Aggregate] + [EmptyResponse]     wolverine/guide/http/marten.md
//   StreamIdentity.AsString                             marten/events/configuration.md
//   self-aggregating Create/Apply snapshots             marten/events/projections/aggregate-projections.md
//   AlbaHost.For<Program> + RunWolverineInSoloMode      wolverine/guide/http/integration-testing.md
//   UseFluentValidationProblemDetailMiddleware          wolverine/guide/http/policies.md
// Testcontainers is NOT in the mirror (zero mentions across 392 pages), so its usage is the one
// part of this file written from unverifiable knowledge. Flagged in the output.

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve, join, dirname } from "node:path";

const [target, ...rest] = process.argv.slice(2);
const flag = (n, d) => { const i = rest.indexOf(`--${n}`); return i >= 0 && rest[i + 1] ? rest[i + 1] : d; };
if (!target) {
  console.error("usage: node tools/codegen.mjs <system-dir> [--out generated/<System>]");
  process.exit(2);
}

// --- the IR is the only input -----------------------------------------------------------------

const irPath = join("build", `${resolve(target).split(/[\\/]/).pop()}.ir.json`);
execFileSync(process.execPath, [join("tools", "model.mjs"), "compile", target], { stdio: "pipe" });
const ir = JSON.parse(readFileSync(irPath, "utf8"));

const pascal = (s) => s.replace(/(^|[^a-zA-Z0-9])([a-z])/g, (_, a, b) => b.toUpperCase()).replace(/[^a-zA-Z0-9]/g, "");
const camel = (s) => { const p = pascal(s); return p[0].toLowerCase() + p.slice(1); };
const NS = pascal(ir.system);
const OUT = resolve(flag("out", join("generated", NS)));
const APP = join(OUT, "src", NS);
const TESTS = join(OUT, "tests", `${NS}.IntegrationTests`);

const CS = {                       // model type -> C# type. Anything unknown stays verbatim.
  Guid: "Guid", string: "string", decimal: "decimal", int: "int", long: "long", bool: "bool",
  DateOnly: "DateOnly", DateTimeOffset: "DateTimeOffset", DateTime: "DateTime",
};
const type = (f) => `${CS[f.type] ?? f.type}${f.nullable ? "?" : ""}`;
const params = (fields) => fields.map((f) => `${type(f)} ${pascal(f.name)}`).join(", ");

const write = (p, body) => { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, body.replace(/\n{3,}/g, "\n\n"), "utf8"); };
const banner = (what) =>
  `// <auto-generated>\n//   ${what}\n//   Generated by tools/codegen.mjs from the event model. Do not edit by hand:\n` +
  `//   re-run codegen and the change is lost. Holes marked TODO(codegen) are for the codegen skill.\n// </auto-generated>\n`;

// Where a rule is enforced. This was going to be derived from given= being empty — a rule needing no
// prior events settles from the request alone — but that fails on a real model: almost every GWT
// carries a CONTEXT given= like "the month is open", so on hour-booking the heuristic found zero
// periphery rules out of four. Declared instead, and defaulting to the safe answer (the aggregate,
// where the stream is visible). A misplaced rule in a validator cannot enforce itself.
const isPeriphery = (g) => (g.enforce ?? "aggregate") === "periphery";

// A slice nobody has started yet still gets its tests generated — they document the rules — but
// skipped, so `dotnet test` going green means the slices that ARE claimed actually pass. The skip
// count is then the honest measure of what is left.
const CLAIMED = new Set(["ready", "in-progress", "in-review", "closed"]);
const isClaimed = (s) => CLAIMED.has(s.status ?? "in-design");
const factAttr = (s) => isClaimed(s)
  ? "[Fact]"
  : `[Fact(Skip = ${JSON.stringify(`slice ${s.name} is ${s.status ?? "in-design"} — nobody has claimed these rules yet`)})]`;
const ruleName = (g) => pascal((/^error:\s*(.+)$/i.exec((g.then ?? "").trim())?.[1] ?? g.rule ?? g.id).trim());
const testName = (g, i) => {
  const base = (g.rule || g.label || g.id).replace(/\s*\n[\s\S]*$/, "");
  return pascal(base.replace(/[^a-zA-Z0-9 ]/g, " ").split(/\s+/).slice(0, 12).join(" ")) || `Rule${i + 1}`;
};

const files = [];
const kept = [];
// Fully derived: always overwritten, because the diff IS the review of a model change.
const emit = (p, body) => { write(p, body); files.push(p); };
// Needs judgement: scaffolded once, then owned by whoever filled it in. Overwriting this would
// silently delete the only part of the code a model cannot express.
//
// The banner is rewritten HERE rather than at each call site, because a fresh scaffold file was being
// born with the <auto-generated> banner — which says "do not edit by hand: re-run codegen and the change
// is lost". That is the exact opposite of true for the one kind of file where editing is the whole point,
// and CLAUDE.md claimed the distinction already existed. Centralising it means no call site can forget.
const scaffold = (p, body) => {
  if (existsSync(p)) { kept.push(p); return; }
  write(p, body
    .replace("// <auto-generated>", "// <auto-generated-scaffold>")
    .replace("// </auto-generated>", "// </auto-generated-scaffold>")
    .replace(
      "//   Generated by tools/codegen.mjs from the event model. Do not edit by hand:\n" +
      "//   re-run codegen and the change is lost. Holes marked TODO(codegen) are for the codegen skill.",
      "//   Scaffolded once by tools/codegen.mjs, then FILLED IN BY HAND — regeneration KEEPS this file.\n" +
      "//   Holes marked TODO(codegen) are yours to close; they are reported until you do."));
  files.push(p);
};

// A GWT added to a slice that is ALREADY implemented gets no test, because the test file is
// scaffold — written once, then hand-owned, and regeneration keeps it. Nothing failed, nothing was
// skipped, and the rule simply had no test. That defeats the one gate the whole kit rests on: "the
// slice's tests are live, not skipped."
//
// Every generated test carries its rule text as a comment, so a kept file can be checked for
// coverage without parsing C#. Reported rather than repaired: appending into a file somebody else
// owns is how a generator destroys hand-written work.
const untested = [];
const checkGwtCoverage = (p, gwts) => {
  if (!existsSync(p)) return;
  const src = readFileSync(p, "utf8");
  for (const g of gwts) if (!src.includes(g.rule)) untested.push({ path: p, rule: g.rule });
};

// An automation nothing ever wakes passes every test it has, because the tests drive the trigger
// directly. The generator deliberately does not choose the mechanism (see the automations block below),
// so the hole it leaves has to be reported until somebody closes it — otherwise "not chosen yet" and
// "chosen and working" look identical from the outside, which is how it shipped once.
//
// Looks for the marker the generator itself wrote, not for any of the four implementation shapes. An
// earlier version grepped for `ScheduleAsync` and therefore fired on every correct non-sweep automation;
// a check that flags correct code is worse than no check.
const unwoken = [];
const checkWakeupChosen = (p, slice) => {
  if (!existsSync(p)) return;                       // not scaffolded yet; this run will write it
  if (readFileSync(p, "utf8").includes("TODO(codegen): choose how"))
    unwoken.push({ path: p, slice });
};

// There WAS a check here for "the trigger never schedules its successor", from when the beat was meant
// to come from the handler rescheduling itself. That design does not work on this stack (see
// AutomationHeartbeat) and the cadence now lives in generated code, so there is no line left for a human
// to forget — and a check that fires on every correct automation is worse than no check.
//
// What replaced it is structural rather than a lint: the generator emits the heartbeat and its
// registration for every automation slice past in-design. The thing still NOT verifiable here is whether
// the clock actually ticks in a running process; only starting the app and watching a second sweep does
// that. ANTI-PATTERNS.md #14.

// --- events -----------------------------------------------------------------------------------

const owned = ir.shared.events.filter((e) => e.ownedBy);
const foreign = ir.shared.events.filter((e) => !e.ownedBy);
emit(join(APP, "Contracts", "Events.cs"),
  `${banner(`${ir.shared.events.length} event records — every distinct event in the system`)}
namespace ${NS}.Contracts;

${owned.map((e) => `/// <summary>${e.aggregate} stream. Produced by ${e.ownedBy}.${e.isPublic ? " Public: other contexts consume it." : ""}</summary>
public sealed record ${pascal(e.label)}(${params(e.fields)});`).join("\n\n")}

// Events we do not produce. We model the incoming contract so it can be deserialised and projected;
// nothing in this system appends them.
${foreign.map((e) => `/// <summary>External — arrives from ${e.origin}. Terminal: we have no control over it.</summary>
public sealed record ${pascal(e.label)}(${params(e.fields)});`).join("\n\n")}
`);

// --- per-slice aggregates ---------------------------------------------------------------------
//
// There is no such thing as "the" aggregate. Wolverine + Marten let every state-change slice fold
// the stream into whatever shape ITS decision needs, and live aggregation means no projection is
// registered for any of them — FetchForWriting folds on demand. So the aggregate is per SLICE, not
// per stream, which also takes it out of the shared layer and makes slices that much more
// independent.
//
// The endpoint is the decider: it receives the folded state and returns events. So a state type is
// a pure left fold and holds no rules.
//
// No Create methods. Marten will build from a no-arg constructor, and its own docs say that is
// "probably safest unless you can guarantee that a certain event type will always be first in the
// event stream" — which does not hold here: the Timesheet stream is opened by HoursBooked or by
// ZeroHoursFilled depending on whether the employee booked anything before leaving a project.

const stateName = (s) => `${pascal(s.name)}State`;
const streamOf = (s) => ir.shared.aggregates.find((a) => a.commands.some((c) => c.label === s.commands[0]));

for (const s of ir.slices) {
  if (!s.generates || !s.commands.length) continue;
  const agg = streamOf(s);
  if (!agg || !agg.events.length) continue;
  const evs = agg.events.map((l) => ir.shared.events.find((e) => e.label === l));
  const keyed = agg.identity;
  scaffold(join(APP, "Slices", pascal(s.context), pascal(s.name), `${stateName(s)}.cs`),
    `${banner(`${s.name} — the state this slice folds to make its decision`)}
using ${NS}.Contracts;

namespace ${NS}.Slices.${pascal(s.context)};

/// <summary>
/// Live aggregation over the ${agg.name} stream, keyed by ${keyed.join(" + ") || "an undeclared identity"}.
/// Nothing registers a projection for this: Marten folds it on demand when the endpoint asks.
///
/// Folds every event of the stream, not only this slice's, because a decision may depend on any of
/// them — the daily cap needs the whole month's bookings, not just the one being added.
///
/// The model draws ${evs[0].label} first in this stream, but there is deliberately no Create method:
/// a no-arg constructor lets any event open the stream.
/// </summary>
public sealed record ${stateName(s)}
{
    public string Id { get; init; } = default!;

    /// <summary>Marten's convention. The aggregate workflow uses it for optimistic concurrency.</summary>
    public int Version { get; set; }

${keyed.length ? `    public static string StreamKey(${keyed.map((k) => {
      const f = evs[0].fields.find((x) => x.name === k);
      return `${f ? type(f) : "string"} ${camel(k)}`;
    }).join(", ")})
        => $"${camel(agg.name)}:${keyed.map((k) => `{${camel(k)}}`).join(":")}";
` : ""}
${evs.map((e) => `    public static ${stateName(s)} Apply(${pascal(e.label)} e, ${stateName(s)} current)
        // TODO(codegen): fold ${pascal(e.label)} into whatever ${pascal(s.commands[0])} needs to decide.
        // Carries: ${e.fields.map((f) => f.name).join(", ")}.
        => current;`).join("\n\n")}
}
`);
}

// --- views ------------------------------------------------------------------------------------

const SYS_KEY = [...new Set(ir.shared.aggregates.flatMap((a) => a.identity))];
const registerable = [];   // views whose projection is valid enough to register inline

for (const v of ir.shared.views) {
  const derived = Object.entries(v.derived ?? {});
  const streams = [...new Set(v.from.map((l) => ir.shared.events.find((e) => e.label === l)?.aggregate).filter(Boolean))];
  // One row is one stream only when the view is keyed as its single feeding stream is. Stream COUNT
  // alone does not say that: WorkingDays is fed from one stream and keyed by date, so one stream holds
  // many rows and the single-stream base class cannot express it.
  //
  // But an undeclared grain is not evidence of a finer one. A view that declares no identity= is
  // assumed to be one row per stream, which is what it was before anyone asked — demanding a match
  // there dropped `Admins` (one row per admin, fed by one stream, grain never declared) to
  // multi-stream with no slicing rule, and the generator then commented its registration out
  // entirely. A stricter check that silently stops projecting a working view is worse than the bug it
  // fixed.
  //
  // So the multi-stream base class is used when there is real evidence of it: several feeding
  // streams, or a declared grain that the single feeding stream's key does not match.
  const streamKey = streams.length === 1
    ? (ir.shared.aggregates.find((a) => a.name === streams[0])?.identity ?? [])
    : [];
  const declared = v.identity?.length ? v.identity : null;
  const rowIsStream = streams.length === 1 && (
    declared === null ||
    (streamKey.length === declared.length && streamKey.every((k) => declared.includes(k))));
  const multi = !rowIsStream;
  const ownKey = declared ?? SYS_KEY;
  // A row of THIS view, not of the system. Declared on the read model where the grain is known;
  // where it is not, fall back to the system key and say so, because guessing a view's grain
  // silently is how a projection ends up grouping the wrong rows together.
  const KEY = v.identity?.length ? v.identity : SYS_KEY;
  const guessedKey = !v.identity?.length;
  const sliceable = v.from.filter((l) => {
    const e = ir.shared.events.find((x) => x.label === l);
    return KEY.every((k) => e?.fields.some((f) => f.name === k));
  });
  if (!multi || sliceable.length) registerable.push(v.label);
  scaffold(join(APP, "Views", `${pascal(v.label)}.cs`),
    `${banner(`${v.label} read model — fed by ${v.from.length} event type(s)`)}
using Marten.Events.Aggregation;   // SingleStreamProjection
using Marten.Events.Projections;   // MultiStreamProjection
using ${NS}.Contracts;

namespace ${NS}.Views;

/// <summary>
/// Context: ${v.context}. Slice: ${v.slice}.
/// Fed by: ${v.from.join(", ")}.${v.todoFor?.length ? `\n/// TODO LIST for the ${v.todoFor.join(", ")} automation: a row here is pending work.` : ""}
/// </summary>
public sealed record ${pascal(v.label)}
{
    public string Id { get; init; } = default!;

${v.fields.map((f) => {
      const d = v.derived?.[f.name];
      return `    /// <summary>${d ? `Computed from ${d.join(" + ")} — not carried by any event.` : "Carried by an upstream event."}</summary>
    public ${type(f)} ${pascal(f.name)} { get; init; }${f.nullable || CS[f.type] === "string" ? " = default!;" : ""}`;
    }).join("\n\n")}
}

${derived.length ? `// ${derived.length} field(s) are derived and the model records their INPUTS, not the arithmetic:
${derived.map(([k, srcs]) => `//   ${k} <- ${srcs.join(" + ")}`).join("\n")}
// A human decides whether each is a sum, a count, a difference or a fold. See OPEN-QUESTIONS.md.
` : ""}
/// <summary>
/// ${multi ? "Multi-stream" : "Single-stream"} projection, registered INLINE in Program.cs: read models are
/// updated in the same transaction as the append, so a GWT's THEN can be asserted immediately.
/// Contrast the write side, which registers nothing and folds live.
${multi ? `///
/// Fed from ${streams.length} streams (${streams.join(", ")}), so events must be grouped explicitly.
/// Grouped by ${KEY.join(" + ")}${guessedKey ? " — GUESSED from the system key, because this read model\n/// declares no identity=. Declare it: a wrong grain groups the wrong rows together." : " (declared on the read model)"}.` : ""}
/// </summary>
public sealed class ${pascal(v.label)}Projection : ${multi
      ? `MultiStreamProjection<${pascal(v.label)}, string>`
      : `SingleStreamProjection<${pascal(v.label)}, string>`}
{
${multi ? `    public ${pascal(v.label)}Projection()
    {
${v.from.map((l) => {
        const e = ir.shared.events.find((x) => x.label === l);
        const has = KEY.every((k) => e?.fields.some((f) => f.name === k));
        return has
          ? `        Identity<${pascal(l)}>(e => $"${KEY.map((k) => `{e.${pascal(k)}}`).join(":")}");`
          : `        // TODO(codegen): ${pascal(l)} carries ${e?.fields.map((f) => f.name).join(", ") || "nothing"} —\n` +
            `        // not ${KEY.join(" + ")}, so how it groups into this view is a decision.\n` +
            `        // Identity<${pascal(l)}>(e => ...);`;
      }).join("\n")}
    }

` : ""}${v.from.map((l) => `    public static ${pascal(v.label)} Apply(${pascal(l)} e, ${pascal(v.label)} current)
        // TODO(codegen): fold ${pascal(l)} into the row.
        => current;`).join("\n\n")}
}
`);
}

// --- validators: the periphery rules ----------------------------------------------------------

const peripheryBySlice = new Map();
for (const s of ir.slices) {
  const p = s.gwts.filter(isPeriphery);
  if (p.length && s.commands.length) peripheryBySlice.set(s, p);
}
// One command record per command, always. Derived from the IR, so emit() and not scaffold().
for (const s of ir.slices) {
  if (!s.generates || !s.commands.length) continue;
  const cmd = s.commands[0];
  const agg = ir.shared.aggregates.find((a) => a.commands.some((c) => c.label === cmd));
  const fields = agg?.commands.find((c) => c.label === cmd)?.fields ?? [];
  emit(join(APP, "Slices", pascal(s.context), pascal(s.name), `${pascal(cmd)}.cs`),
    `${banner(`${cmd} — the command as the model declares it`)}
namespace ${NS}.Slices.${pascal(s.context)};

/// <summary>
/// Slice: ${s.name}. Fields exactly as the model declares them: ${fields.map((f) => f.name).join(", ") || "none"}.
/// Emitted for every command, whether or not the slice has periphery rules — a validator-free
/// command still needs a type.
/// </summary>
public sealed record ${pascal(cmd)}(${params(fields)});
`);
}

for (const [s, gwts] of peripheryBySlice) {
  const cmd = s.commands[0];
  const agg = ir.shared.aggregates.find((a) => a.commands.some((c) => c.label === cmd));
  const fields = agg?.commands.find((c) => c.label === cmd)?.fields ?? [];
  scaffold(join(APP, "Slices", pascal(s.context), pascal(s.name), `${pascal(cmd)}Validator.cs`),
    `${banner(`${cmd} — periphery validation for slice "${s.name}"`)}
using FluentValidation;

// The CONTEXT namespace, not a per-slice one. A per-slice namespace collides with the command record
// itself whenever the slice and its command share a name — prepare-email / PrepareEmail, book-hours /
// BookHours — which is the normal case, not an edge one. Declaring namespace X.Y.PrepareEmail puts a
// member PrepareEmail in X.Y, where the record already lives: CS0101.
//
// This shipped broken for months because the validator is SCAFFOLD: the first agent to hit it fixed the
// namespace by hand, its project went green, and the generator never learned. A hand fix to a scaffold
// file does not feed back — see ANTI-PATTERNS.md #13 for the same shape.
namespace ${NS}.Slices.${pascal(s.context)};

/// <summary>
/// Only rules that need nothing but the request. A GWT with no GIVEN is a statement about the
/// message alone, so it can be rejected before any stream is read. Rules whose GIVEN names events
/// are decisions about accumulated state and live in the endpoint, where the aggregate is visible.
/// </summary>
public sealed class ${pascal(cmd)}Validator : AbstractValidator<${pascal(cmd)}>
{
    public ${pascal(cmd)}Validator()
    {
${gwts.map((g) => `        // ${ruleName(g)}: ${(g.rule ?? "").replace(/\s+/g, " ")}
        // TODO(codegen): RuleFor(x => x.?).Must(...).WithMessage("${ruleName(g)}");`).join("\n\n")}
    }
}

// The ${pascal(cmd)} record itself is emitted next door, per command rather than per validator.
`);
}

// --- the Alba harness -------------------------------------------------------------------------

emit(join(TESTS, "AppFixture.cs"),
  `${banner("Alba + Testcontainers harness shared across the whole test collection")}
using Alba;
using JasperFx.CommandLine;
using Marten;
using Marten.Schema;
using Microsoft.Extensions.DependencyInjection;
using Testcontainers.PostgreSql;
using Wolverine;
using Xunit;

namespace ${NS}.IntegrationTests;

/// <summary>
/// One Postgres for the whole assembly, and one host. Building either per test is the difference
/// between a suite that runs in seconds and one nobody waits for.
///
/// This container is NOT the docker-compose Postgres. They must never share a connection string:
/// Marten manages schema, so a test run pointed at the demo database would drop the demo data, and
/// Testcontainers owns a lifecycle that compose would fight.
/// </summary>
public sealed class AppFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .WithDatabase("${camel(ir.system)}_tests")
        .Build();

    public IAlbaHost Host { get; private set; } = null!;

    public async Task InitializeAsync()
    {
        await _postgres.StartAsync();

        // Required when the app uses JasperFx command line integration.
        JasperFxEnvironment.AutoStartHost = true;

        Host = await AlbaHost.For<Program>(builder =>
        {
            builder.ConfigureServices(services =>
            {
                // Solo mode skips leader election and the durability agents: much faster startup.
                services.RunWolverineInSoloMode();
                // No broker in tests. Sends are still tracked, just not delivered.
                services.DisableAllExternalWolverineTransports();

                // Marten attaches any IInitialData in the container to StoreOptions, and
                // ResetAllMartenDataAsync re-applies it — so every test starts in the same world.
                services.AddSingleton<IInitialData, SeedData>();
            });
            builder.UseSetting("ConnectionStrings:Marten", _postgres.GetConnectionString());

            // No automation CLOCK in tests, whatever mechanism a slice chose. Anything firing on its own
            // mid-test appends events into streams other slices are asserting on, and every GIVEN in the
            // suite becomes a race. Tests send the Run<Slice> message themselves — the same message every
            // mechanism ends up sending, to the same trigger — so the production path is still the tested
            // path. Only the clock is absent, and a clock is the one part of an automation a test must
            // control rather than observe.
            builder.UseSetting("Automation:Wakeup", "false");
        });
    }

    public async Task DisposeAsync()
    {
        await Host.StopAsync();
        await Host.DisposeAsync();
        await _postgres.DisposeAsync();
    }
}

[CollectionDefinition("integration")]
public sealed class IntegrationCollection : ICollectionFixture<AppFixture>;
`);

// Marten's IInitialData is the answer to "a test needs example data and the model has none". The
// genesis events are seeded once with fixed ids, ResetAllData re-applies them, and every test then
// starts from the same known world instead of inventing its own.
scaffold(join(TESTS, "SeedData.cs"),
  `${banner("baseline data — one known world, re-applied before every test")}
using Marten;
using Marten.Schema;
using ${NS}.Contracts;

namespace ${NS}.IntegrationTests;

/// <summary>
/// Fixed ids so a GIVEN can name things, and so a failing test is reproducible. The model declares
/// field names and types but never example values — this is where the values live, once.
///
/// Seeds only the ${foreign.length} events nothing in this system produces (${foreign.map((e) => e.label).join(", ")}).
/// Everything else is appended by the test's own GIVEN, because that is what a GIVEN is for.
/// </summary>
public sealed class SeedData : IInitialData
{
    public static readonly Guid EmployeeId = Guid.Parse("11111111-1111-1111-1111-111111111111");
    public static readonly Guid OtherEmployeeId = Guid.Parse("22222222-2222-2222-2222-222222222222");
    public static readonly Guid ProjectId = Guid.Parse("33333333-3333-3333-3333-333333333333");
    public static readonly Guid OtherProjectId = Guid.Parse("44444444-4444-4444-4444-444444444444");
    public static readonly Guid AdminId = Guid.Parse("55555555-5555-5555-5555-555555555555");

    public const string Month = "2026-08";
    public static readonly DateOnly WorkingDay = new(2026, 8, 3);
    public static readonly DateOnly SecondWorkingDay = new(2026, 8, 4);
    public static readonly DateTimeOffset SeededAt = new(2026, 8, 1, 0, 0, 0, TimeSpan.Zero);

    public async Task Populate(IDocumentStore store, CancellationToken cancellation)
    {
        await using var session = store.LightweightSession();

        // TODO(codegen): append the foreign events above onto whatever streams the model says they
        // land in. They have origin=, not from=, so nothing here produces them — they are the world
        // this system wakes up in.

        await session.SaveChangesAsync(cancellation);
    }
}
`);

emit(join(TESTS, "IntegrationContext.cs"),
  `${banner("Base class for every GWT test")}
using Alba;
using Marten;
using Microsoft.Extensions.DependencyInjection;
using Wolverine.Tracking;
using Xunit;

namespace ${NS}.IntegrationTests;

[Collection("integration")]
public abstract class IntegrationContext(AppFixture fixture) : IAsyncLifetime
{
    protected IAlbaHost Host => fixture.Host;
    protected IDocumentStore Store => Host.Services.GetRequiredService<IDocumentStore>();

    /// <summary>Every test starts from an empty event store, so GIVEN means exactly what it says.</summary>
    public Task InitializeAsync() => Host.ResetAllMartenDataAsync();

    public Task DisposeAsync() => Task.CompletedTask;

    /// <summary>
    /// GIVEN: append prior events straight to the stream, bypassing the endpoints. A GWT's GIVEN is
    /// history, not a sequence of requests to replay.
    /// </summary>
    protected async Task Given(string streamKey, params object[] events)
    {
        await using var session = Store.LightweightSession();
        session.Events.Append(streamKey, events);
        await session.SaveChangesAsync();
    }

    /// <summary>THEN: the events a stream actually holds, in order.</summary>
    protected async Task<object[]> EventsFor(string streamKey)
    {
        await using var session = Store.QuerySession();
        var raw = await session.Events.FetchStreamAsync(streamKey);
        return raw.Select(x => x.Data).ToArray();
    }

    /// <summary>
    /// WHEN: an HTTP call that waits for ALL cascading Wolverine work before returning. Not an Alba
    /// extension — Alba makes the request, Wolverine.ExecuteAndWaitAsync wraps it and blocks until
    /// every message published or cascaded as a result has finished. Without the wrapper an
    /// assertion can run before the projection it is asserting on has been updated.
    /// </summary>
    protected async Task<(ITrackedSession, IScenarioResult)> WhenPosting(
        Action<Scenario> configure, int timeoutInMilliseconds = 10000)
    {
        IScenarioResult result = null!;
        var tracked = await Host.ExecuteAndWaitAsync(
            async () => { result = await Host.Scenario(configure); }, timeoutInMilliseconds);
        return (tracked, result);
    }
}
`);

// --- one test per GWT -------------------------------------------------------------------------

let gwtCount = 0;
for (const s of ir.slices) {
  if (!s.gwts.length) continue;
  const agg = ir.shared.aggregates.find((a) => a.commands.some((c) => s.commands.includes(c.label)));
  const key = (s.commands.length && agg?.identity.length)
    ? `${stateName(s)}.StreamKey(/* ${agg.identity.join(", ")} */)`
    : "/* no command in this slice, so no stream is written */";
  gwtCount += s.gwts.length;
  checkGwtCoverage(join(TESTS, "Slices", pascal(s.context), `${pascal(s.name)}Tests.cs`), s.gwts);
  scaffold(join(TESTS, "Slices", pascal(s.context), `${pascal(s.name)}Tests.cs`),
    `${banner(`slice "${s.name}" — ${s.gwts.length} GWT(s), one test each`)}
using Alba;
using ${NS}.Contracts;
using ${NS}.Slices.${pascal(s.context)};
using Shouldly;
using Xunit;

namespace ${NS}.IntegrationTests.Slices.${pascal(s.context)};

/// <summary>
/// Generated from the model's GWT cells, NOT from the implementation — which is the only reason
/// these tests mean anything. Pattern: ${s.pattern}. Status: ${s.status}.
/// ${isClaimed(s) ? "LIVE: this slice is claimed, so every test here must pass." : "SKIPPED: promote the slice past in-design to turn these on."}
/// ${s.owners.length > 1 ? `This slice needs ${s.owners.join(" and ")}, so these are the contract between them.` : `Owned by ${s.owner ?? "nobody in particular"}.`}
/// </summary>
public sealed class ${pascal(s.name)}Tests(AppFixture fixture) : IntegrationContext(fixture)
{
${s.gwts.map((g, i) => {
      const thens = (g.then ?? "").split(",").map((x) => x.trim()).filter(Boolean);
      const err = thens.find((t) => /^error:/i.test(t));
      return `    // ${(g.rule || g.label || g.id).replace(/\s+/g, " ")}
    //   GIVEN ${g.given || "(nothing)"}
    //   WHEN  ${g.when || "(nothing)"}
    //   THEN  ${g.then || "(nothing)"}${isPeriphery(g) ? "\n    //   No GIVEN, so this is a periphery rule: expect 400 from the validator." : ""}
    ${factAttr(s)}
    public Task ${testName(g, i)}()
        => throw new NotImplementedException(
            "TODO(codegen): ${err ? `expect a 400/ProblemDetails for ${ruleName(g)}` : `expect ${thens.join(", ") || "the modelled outcome"}`}. " +
            "Stream key: ${key.replace(/"/g, "'")}. Use SeedData.EmployeeId / SeedData.Month / SeedData.ProjectId / SeedData.WorkingDay for values.");`;
    }).join("\n\n")}
}
`);
}

// --- automation heartbeats --------------------------------------------------------------------

// An automation that only runs when a human POSTs to a route is not an automation. What wakes the
// processor is transport and the model says nothing about it — but that a `pattern="automation"`
// slice needs SOMETHING to wake it is mechanically derivable, so the generator owns it rather than
// leaving it to whoever remembers.
//
// Only slices past in-design get one: the message has no handler until the slice is implemented, and
// Wolverine asserts a subscriber exists.
const automations = ir.slices.filter(
  (s) => s.pattern === "automation" && s.status !== "in-design");
const sweepMessage = (s) => `Run${pascal(s.name)}`;
// THE GENERATOR DOES NOT CHOOSE HOW A TRIGGER IS WOKEN, and that is a deliberate reversal.
//
// It used to emit an AutomationHeartbeat — a clock-driven sweep — for every automation slice. That was
// generalised from a single model whose automations were all triggered by FOREIGN events or by the
// PASSAGE OF TIME, which is a property of that model and not of the pattern. Event forwarding, a Marten
// subscription and projection RaiseSideEffects are all valid, and the right one depends on the slice:
// see the decision table in .claude/agents/backend-agent.md, and the worked comparison in
// reference-implementations/automation/.
//
// What IS derivable, and so still generated:
//
//   * Run<Slice>, the message the trigger handles. Every mechanism ends up invoking the same trigger,
//     so this is the one seam all four share — and it is what lets a test drive the production path.
//   * Discovery.IncludeType for the trigger class, because conventional discovery only finds
//     *Handler / *Consumer and a processor named after its automation cell is neither.
//   * a Register hook per slice, called from Program.cs, whose BODY is scaffold.
//
// What is not: the body of that hook. It carries a TODO(codegen) marker, and the marker is reported
// until somebody removes it — so "nothing wakes this" is caught at generation time instead of
// surviving a green test suite, which is exactly how it got through once.
if (automations.length) {
  emit(join(APP, "Contracts", "AutomationMessages.cs"),
    `${banner(`${automations.length} automation trigger message(s) — one per automation slice`)}
namespace ${NS}.Contracts;

${automations.map((s) => `/// <summary>
/// Runs the ${s.name} trigger once: read the View, issue commands for whatever is outstanding.
///
/// It carries nothing on purpose. The trigger decides from ACCUMULATED STATE — that is what makes it an
/// automation rather than an event handler — so anything this message carried would be a second source of
/// truth competing with the View.
///
/// Whatever wakes the trigger sends this: a forwarded event, a subscription, a projection side effect or a
/// clock. See ${pascal(s.name)}Wakeup.
/// </summary>
public sealed record ${sweepMessage(s)};`).join("\n\n")}
`);

  for (const s of automations) {
    // The TRIGGER class. Program.cs registers it by name, so a project without it does not compile —
    // and for a long time the generator emitted the registration and not the class, which only ever
    // worked because the first project's trigger happened to be written by hand.
    for (const a of s.automations ?? []) {
      scaffold(join(APP, "Slices", pascal(s.context), pascal(s.name), `${a}.cs`),
        `${banner(`${a} — the automated trigger for slice "${s.name}"`)}
#nullable enable
using Marten;
using Wolverine;
using ${NS}.Contracts;
using ${NS}.Views;

namespace ${NS}.Slices.${pascal(s.context)};

/// <summary>
/// The Automated Trigger of ${s.name}: <c>Event(s) -> View -> TRIGGER -> Command -> Event(s)</c>.
///
/// It is a peer of a person at a screen — it reads a View and issues a Command. It never takes an event as
/// input and never appends one; <c>Event -> Processor -> Event</c> is the classic anti-pattern.
///
/// <see cref="IQuerySession"/> and not <see cref="IDocumentSession"/> on purpose: that makes "a trigger
/// never appends" a compile error rather than a convention. The events come from the decider, reached
/// through the command.
///
/// Returns <see cref="Task"/> and NOT a result object. Wolverine treats a handler's return value as a
/// CASCADING MESSAGE with no opt-out, so a report returned from a fire-and-forget run is unroutable and
/// takes the whole outgoing batch with it. If a human needs to see what a run did, log it or give the run
/// its own operational route.
///
/// What wakes this is NOT here: see ${pascal(s.name)}Wakeup.
/// </summary>
public static class ${a}
{
    public static async Task Handle(
        ${sweepMessage(s)} message,
        IQuerySession session,
        IMessageBus bus,
        ILogger logger,
        CancellationToken cancellation)
    {
        // TODO(codegen): read the slice's View for outstanding work, and issue its Command per item.
        //
        //   var work = await session.Query<SomeTodoView>().Where(r => r.IsPending).ToListAsync(cancellation);
        //   foreach (var row in work) await bus.InvokeAsync(new SomeCommand(row.Id), cancellation);
        //
        // Two things that are not optional:
        //   * the run must be safe to REPEAT. At-least-once is the normal case for every wakeup mechanism,
        //     so correctness cannot depend on how often this fires.
        //   * log every run, including one that did nothing — otherwise "alive with no work" and "dead"
        //     produce identical output, and that ambiguity has hidden a broken wakeup before.
        await Task.CompletedTask;
        logger.LogInformation("${s.name}: nothing implemented yet.");
    }
}
`);
    }

    const p = join(APP, "Automation", `${pascal(s.name)}Wakeup.cs`);
    checkWakeupChosen(p, s.name);
    scaffold(p,
      `${banner(`${s.name} — HOW this automation is woken. Choose one; regeneration keeps this file.`)}
#nullable enable
using Wolverine;
using ${NS}.Contracts;

namespace ${NS}.Automation;

/// <summary>
/// The one thing the model does not tell you about an automation slice.
///
/// \`Event(s) -> View -> Trigger -> Command\` constrains the CONTRACT: the trigger decides from accumulated
/// state rather than from one event's payload, and issues a command rather than appending one. It says
/// nothing about what wakes the trigger, and it does not require the View to be a materialised projection —
/// a subscription's checkpoint is a record of what has been worked, a durable inbox is a list of pending
/// work. The green box on the diagram is the concept.
///
/// So this is an implementation choice, not a domain fact, which is why it lives in code and not on a cell.
/// Pick the row you are in:
///
///   the trigger event is OURS, appended in our own transaction   -> event forwarding to a handler
///   ours, and ordering or replay matters                         -> Marten ISubscription
///   ours, and the decision is a function of the VIEW ROW         -> projection RaiseSideEffects
///   the trigger event is FOREIGN — we never append it            -> sweep the View on a clock
///   there is no event at all — the trigger is TIME               -> sweep
///
/// Worked implementations of all of these, against one shared model, are in
/// reference-implementations/automation/. Read that before writing this.
///
/// Whatever you choose, it must end up sending <see cref="${sweepMessage(s)}"/>. Keeping that seam means a
/// test drives the same path production does — and while the trigger was reachable only over HTTP, "nothing
/// ever wakes this in production" was invisible to a green suite.
///
/// TWO RULES THAT HOLD FOR EVERY CHOICE:
///   * a clock must be absent in tests, or a run firing mid-test turns every other slice's GIVEN into a
///     race. Gate it on configuration and let tests send ${sweepMessage(s)} themselves.
///   * whatever you register, the run must be safe to repeat. At-least-once is the normal case for all of
///     these, so correctness cannot depend on how often it fires.
/// </summary>
public static class ${pascal(s.name)}Wakeup
{
    public static void Register(WebApplicationBuilder builder)
    {
        // TODO(codegen): choose how ${s.name} is woken, then delete this line.
        //
        // Until it is gone, \`node tools/codegen.mjs\` reports this slice under AUTOMATION NOT WOKEN —
        // because an automation nothing ever runs passes every test it has.
    }
}
`);
  }
}


// Development seed data. Program.cs constructs this under IsDevelopment, so a project without it does
// not compile — another type the generator referenced and never wrote. Scaffold, because the VALUES are a
// judgement the model deliberately does not carry: it declares field names and types and never examples.
scaffold(join(APP, "GenesisData.cs"),
  `${banner("development-only starting data — a world to click around in")}
#nullable enable
using Marten;
using Marten.Schema;
using ${NS}.Contracts;

namespace ${NS};

/// <summary>
/// A lived-in world for running the app by hand. NOT used by the tests — they have their own SeedData with
/// fixed ids, because a test needs a world it controls and a demo needs one that looks used.
///
/// Attached via <c>.InitializeWith(...)</c> on the Marten chain. Registering an IInitialData in the DI
/// container alone does nothing.
/// </summary>
public sealed class GenesisData : IInitialData
{
    public async Task Populate(IDocumentStore store, CancellationToken cancellation)
    {
        // Populate runs on EVERY startup, so this has to be idempotent.
        //
        // Careful with the usual guard — "if any row of view X exists, return". It fires on the OLD data,
        // so genesis events added later never land on an existing demo database and the feature that needs
        // them looks broken. \`docker compose down -v\` is the fix; knowing that is cheaper than debugging it.
        await using var query = store.QuerySession();

        // TODO(codegen): seed the foreign/genesis events this system reads but never produces, plus enough
        // of its own history to make the screens worth looking at. The model names the fields; the values
        // are yours.
        await Task.CompletedTask;
    }
}
`);

emit(join(APP, "Program.cs"),
  `${banner("application bootstrapping")}
using JasperFx;
using JasperFx.Resources;
using JasperFx.Events;
using Weasel.Core;
using JasperFx.Events.Projections;
using Marten;
using Wolverine;
using Wolverine.FluentValidation;
using Wolverine.Http;
using Wolverine.Http.FluentValidation;
using Marten.Schema;
using Wolverine.Marten;
using ${NS};
using ${NS}.Views;${automations.length ? `
using ${NS}.Automation;
${[...new Set(automations.map((s) => `using ${NS}.Slices.${pascal(s.context)};`))].join("\n")}` : ""}

var builder = WebApplication.CreateBuilder(args);

var marten = builder.Services.AddMarten(opts =>
    {
        opts.Connection(builder.Configuration.GetConnectionString("Marten")!);
        opts.DatabaseSchemaName = "${camel(ir.system)}";

        // Every stream in this system is keyed by a composite of model fields, so stream ids are
        // strings. Marten fixes this once per store — Guid and string streams cannot be mixed.
${[...new Set(ir.shared.aggregates.filter((a) => a.identity.length).map((a) => a.identity.join(" + ")))]
      .map((k) => `        //   ${k}`).join("\n")}
        opts.Events.StreamIdentity = StreamIdentity.AsString;

        // StreamOne/StreamMany write Marten's RAW JSON to the response, which bypasses ASP.NET's
        // camelCase policy entirely. Set the casing here or every read endpoint quietly returns
        // PascalCase and the front end silently reads undefined.
        opts.UseSystemTextJsonForSerialization(EnumStorage.AsString, Casing.CamelCase);

        // Read side: every read model is an INLINE projection, updated in the same transaction as
        // the append, so a GWT THEN can be asserted straight after the request returns.
        // Write side registers NOTHING: the per-slice state types are folded live on demand.
${ir.shared.views.map((v) => registerable.includes(v.label)
      ? `        opts.Projections.Add<${pascal(v.label)}Projection>(ProjectionLifecycle.Inline);`
      : `        // TODO(codegen): ${pascal(v.label)}Projection groups events that do not carry
        // ${SYS_KEY.join(" + ")}, so it has no slicing rule yet. Marten rejects a multi-stream
        // projection with no rules AT STARTUP, so registering it now would take the host down.
        // opts.Projections.Add<${pascal(v.label)}Projection>(ProjectionLifecycle.Inline);`
    ).join("\n")}
    })
    .IntegrateWithWolverine();

// Starting data for running the app by hand: membership, an open month, one booking. Development
// only, and idempotent, because Populate runs on every startup.
if (builder.Environment.IsDevelopment()) marten.InitializeWith(new GenesisData());

builder.Services.AddResourceSetupOnStartup();

builder.Host.UseWolverine(opts =>
{
    opts.Policies.AutoApplyTransactions();
    opts.Policies.UseDurableLocalQueues();
    opts.UseFluentValidation();
${automations.length === 0 ? "" : `
    // An automation's trigger is a Wolverine message handler, but its class is named after the
    // automation cell on the model — ZeroFillProcessor, AdminNotifier — and Wolverine's conventional
    // discovery only finds types called *Handler or *Consumer. Registering them explicitly keeps the
    // model's vocabulary in the code instead of renaming a domain concept to suit a scanning rule.
    //
    // typeof(), not IncludeType<T>(): a Wolverine handler class is static, and a static type cannot be
    // a generic argument.
${automations.flatMap((s) => (s.automations ?? []).map(
  (a) => `    opts.Discovery.IncludeType(typeof(${a}));`)).join("\n")}`}
});

builder.Services.AddWolverineHttp();

${automations.length === 0 ? "// No automation slice is past in-design, so nothing needs waking." :
`// HOW EACH AUTOMATION IS WOKEN — one hook per slice, and the generator deliberately does NOT choose.
//
// The model constrains the contract, not the mechanism: it says the trigger decides from accumulated
// state and issues a command, and says nothing about what wakes it. Event forwarding, a Marten
// subscription, projection RaiseSideEffects and a clock-driven sweep are all valid; which is right
// depends on whether the trigger event is ours, whether ordering matters, and whether the trigger is an
// event at all rather than the passage of time.
//
// Each Register body is SCAFFOLD — hand-owned, kept by regeneration — and carries the decision table
// plus a TODO(codegen) marker that codegen reports until it is gone. Worked implementations of all four
// against one shared model: reference-implementations/automation/.
${automations.map((s) => `${pascal(s.name)}Wakeup.Register(builder);`).join("\n")}`}

if (builder.Environment.IsDevelopment())
{
    // The Vite dev server is a different origin. Development only — never a wildcard in production.
    builder.Services.AddCors(o => o.AddDefaultPolicy(p => p
        .WithOrigins("http://localhost:5173")
        .AllowAnyHeader()
        .AllowAnyMethod()));
}

var app = builder.Build();

if (app.Environment.IsDevelopment()) app.UseCors();

app.MapWolverineEndpoints(opts =>
{
    // Turns a failed FluentValidation validator into a 400 with ProblemDetails.
    opts.UseFluentValidationProblemDetailMiddleware();
});

return await app.RunJasperFxCommands(args);
`);

emit(join(APP, "appsettings.json"),
  JSON.stringify({
    ConnectionStrings: { Marten: "Host=localhost;Port=5433;Database=" + camel(ir.system).toLowerCase() + ";Username=postgres;Password=postgres" },
    Logging: { LogLevel: { Default: "Information", "Microsoft.AspNetCore": "Warning" } },
  }, null, 2) + "\n");

emit(join(APP, `${NS}.csproj`),
  `<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>${NS}</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="8.*" />
    <PackageReference Include="Marten.AspNetCore" Version="8.*" />
    <PackageReference Include="WolverineFx.Http" Version="5.*" />
    <PackageReference Include="WolverineFx.Http.Marten" Version="5.*" />
    <PackageReference Include="WolverineFx.Http.FluentValidation" Version="5.*" />
    <PackageReference Include="WolverineFx.Marten" Version="5.*" />
    <PackageReference Include="WolverineFx.FluentValidation" Version="5.*" />
  </ItemGroup>

</Project>
`);

emit(join(TESTS, `${NS}.IntegrationTests.csproj`),
  `<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>${NS}.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alba" Version="8.*" />
    <PackageReference Include="WolverineFx" Version="5.*" />
    <PackageReference Include="JasperFx" Version="1.*" />
    <PackageReference Include="Shouldly" Version="4.*" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\..\\src\\${NS}\\${NS}.csproj" />
  </ItemGroup>

</Project>
`);

// The XML solution format, because a classic .sln is GUID soup that no generator should emit and no
// human should diff.
emit(join(OUT, `${NS}.slnx`),
  `<Solution>
  <Project Path="src/${NS}/${NS}.csproj" />
  <Project Path="tests/${NS}.IntegrationTests/${NS}.IntegrationTests.csproj" />
</Solution>
`);

console.log(`${files.length} file(s) written, ${kept.length} kept (already filled in) -> ${OUT}`);
console.log(`  ${ir.shared.events.length} event records (${owned.length} ours, ${foreign.length} foreign)`);
console.log(`  ${ir.shared.aggregates.filter((a) => a.events.length).length} aggregates, ${ir.shared.views.length} views`);
console.log(`  ${peripheryBySlice.size} validator(s) for periphery rules`);
console.log(`  ${gwtCount} GWT test(s) across ${ir.slices.filter((s) => s.gwts.length).length} slice(s)`);

if (untested.length) {
  console.log(`\nGWT WITHOUT A TEST — ${untested.length}. These rules are in the model and in no test file,`);
  console.log(`because the test file was scaffolded before the GWT was added and is now hand-owned.`);
  console.log(`A green run does NOT cover them. Add each by hand, next to the tests already there:`);
  let last = null;
  for (const u of untested) {
    if (u.path !== last) { console.log(`  ${u.path.replace(OUT, "").replace(/^[\\/]/, "")}`); last = u.path; }
    console.log(`    - ${u.rule}`);
  }
}

if (unwoken.length) {
  console.log(`\nAUTOMATION NOT WOKEN — ${unwoken.length}. Nothing runs these slices, and their tests still pass,`);
  console.log(`because a test drives the trigger directly. Choose a mechanism — the decision table is in the`);
  console.log(`file, and worked implementations are in reference-implementations/automation/:`);
  for (const u of unwoken)
    console.log(`  ${u.slice}: ${u.path.replace(OUT, "").replace(/^[\\/]/, "")}`);
}

console.log(`\nNOTE: Testcontainers is not in reference/llms/ — that harness is the one part written`);
console.log(`      from unverifiable knowledge. Everything else cites a mirrored page.`);
