#!/usr/bin/env node
// Generate the deterministic half of the code from the system IR.
//
//   node tools/codegen.mjs <system-dir> [--out generated/<System>]
//
// The split matters. Anything mechanically derivable from the model belongs in a SCRIPT: it is
// total, idempotent, and its diff is how a model change gets reviewed. Anything needing judgement —
// the body of a business rule, the arithmetic behind a derived field, the example data a test needs
// — belongs to the `codegen` skill, which reads reference/llms/ and fills the marked holes.
//
// So this emits: the solution, both projects, Program.cs, every event record, every aggregate's
// Create/Apply skeleton, every view type, every validator for a periphery rule, the Alba harness,
// and one test per GWT. It emits NO business logic, and says so at every hole with TODO(codegen).
//
// API shapes here are taken from reference/llms/, never from memory:
//   [WolverinePost] + [Aggregate] + [EmptyResponse]     wolverine/guide/http/marten.md
//   StreamIdentity.AsString                             marten/events/configuration.md
//   self-aggregating Create/Apply snapshots             marten/events/projections/aggregate-projections.md
//   AlbaHost.For<Program> + RunWolverineInSoloMode      wolverine/guide/http/integration-testing.md
//   UseFluentValidationProblemDetailMiddleware          wolverine/guide/http/policies.md
// Testcontainers is NOT in the mirror (zero mentions across 392 pages), so its usage is the one
// part of this file written from unverifiable knowledge. Flagged in the output.

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve, join, dirname } from "node:path";

const [target, ...rest] = process.argv.slice(2);
const flag = (n, d) => { const i = rest.indexOf(`--${n}`); return i >= 0 && rest[i + 1] ? rest[i + 1] : d; };
if (!target) {
  console.error("usage: node tools/codegen.mjs <system-dir> [--out generated/<System>]");
  process.exit(2);
}

// --- the IR is the only input -----------------------------------------------------------------

const irPath = join("build", `${resolve(target).split(/[\\/]/).pop()}.ir.json`);
execFileSync(process.execPath, [join("tools", "model.mjs"), "compile", target], { stdio: "pipe" });
const ir = JSON.parse(readFileSync(irPath, "utf8"));

const pascal = (s) => s.replace(/(^|[^a-zA-Z0-9])([a-z])/g, (_, a, b) => b.toUpperCase()).replace(/[^a-zA-Z0-9]/g, "");
const camel = (s) => { const p = pascal(s); return p[0].toLowerCase() + p.slice(1); };
const NS = pascal(ir.system);
const OUT = resolve(flag("out", join("generated", NS)));
const APP = join(OUT, "src", NS);
const TESTS = join(OUT, "tests", `${NS}.IntegrationTests`);

const CS = {                       // model type -> C# type. Anything unknown stays verbatim.
  Guid: "Guid", string: "string", decimal: "decimal", int: "int", long: "long", bool: "bool",
  DateOnly: "DateOnly", DateTimeOffset: "DateTimeOffset", DateTime: "DateTime",
};
const type = (f) => `${CS[f.type] ?? f.type}${f.nullable ? "?" : ""}`;
const params = (fields) => fields.map((f) => `${type(f)} ${pascal(f.name)}`).join(", ");

const write = (p, body) => { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, body.replace(/\n{3,}/g, "\n\n"), "utf8"); };
const banner = (what) =>
  `// <auto-generated>\n//   ${what}\n//   Generated by tools/codegen.mjs from the event model. Do not edit by hand:\n` +
  `//   re-run codegen and the change is lost. Holes marked TODO(codegen) are for the codegen skill.\n// </auto-generated>\n`;

// Where a rule is enforced. This was going to be derived from given= being empty — a rule needing no
// prior events settles from the request alone — but that fails on a real model: almost every GWT
// carries a CONTEXT given= like "the month is open", so on hour-booking the heuristic found zero
// periphery rules out of four. Declared instead, and defaulting to the safe answer (the aggregate,
// where the stream is visible). A misplaced rule in a validator cannot enforce itself.
const isPeriphery = (g) => (g.enforce ?? "aggregate") === "periphery";
const ruleName = (g) => pascal((/^error:\s*(.+)$/i.exec((g.then ?? "").trim())?.[1] ?? g.rule ?? g.id).trim());
const testName = (g, i) => {
  const base = (g.rule || g.label || g.id).replace(/\s*\n[\s\S]*$/, "");
  return pascal(base.replace(/[^a-zA-Z0-9 ]/g, " ").split(/\s+/).slice(0, 12).join(" ")) || `Rule${i + 1}`;
};

const files = [];
const emit = (p, body) => { write(p, body); files.push(p); };

// --- events -----------------------------------------------------------------------------------

const owned = ir.shared.events.filter((e) => e.ownedBy);
const foreign = ir.shared.events.filter((e) => !e.ownedBy);
emit(join(APP, "Contracts", "Events.cs"),
  `${banner(`${ir.shared.events.length} event records — every distinct event in the system`)}
namespace ${NS}.Contracts;

${owned.map((e) => `/// <summary>${e.aggregate} stream. Produced by ${e.ownedBy}.${e.isPublic ? " Public: other contexts consume it." : ""}</summary>
public sealed record ${pascal(e.label)}(${params(e.fields)});`).join("\n\n")}

// Events we do not produce. We model the incoming contract so it can be deserialised and projected;
// nothing in this system appends them.
${foreign.map((e) => `/// <summary>External — arrives from ${e.origin}. Terminal: we have no control over it.</summary>
public sealed record ${pascal(e.label)}(${params(e.fields)});`).join("\n\n")}
`);

// --- aggregates -------------------------------------------------------------------------------
//
// In Wolverine's aggregate handler workflow the ENDPOINT is the decider: it receives the aggregate
// and returns events. So an aggregate is a pure left fold — Create/Apply and nothing else. No
// business rules live here.

for (const a of ir.shared.aggregates.filter((x) => x.events.length)) {
  const evs = a.events.map((l) => ir.shared.events.find((e) => e.label === l));
  const keyed = a.identity.length ? a.identity : null;
  emit(join(APP, "Aggregates", `${pascal(a.name)}.cs`),
    `${banner(`${a.name} aggregate — a left fold over the ${a.name} stream`)}
using ${NS}.Contracts;

namespace ${NS}.Aggregates;

/// <summary>
/// Stream identity: ${keyed ? keyed.join(" + ") : "UNDECLARED — see identity= on the swimlane"}.
/// Streams are string-keyed (Marten StreamIdentity.AsString) because the key is composite.
/// </summary>
public sealed record ${pascal(a.name)}
{
    public string Id { get; init; } = default!;

    /// <summary>Marten sets this by convention; the aggregate workflow uses it for optimistic concurrency.</summary>
    public int Version { get; set; }

${keyed ? `    public static string StreamKey(${keyed.map((k) => {
      const f = evs[0].fields.find((x) => x.name === k);
      return `${f ? type(f) : "string"} ${camel(k)}`;
    }).join(", ")})
        => $"${camel(a.name)}:${keyed.map((k) => `{${camel(k)}}`).join(":")}";
` : ""}
    // TODO(codegen): which event opens this stream? Marten needs exactly one Create for the first
    // event of a stream. Candidates, in the order the model draws them: ${a.events.join(", ")}.
    // The model does not say, so it is not guessed here.

${evs.map((e) => `    public static ${pascal(a.name)} Apply(${pascal(e.label)} e, ${pascal(a.name)} current)
        // TODO(codegen): fold ${pascal(e.label)} into the aggregate. Carries: ${e.fields.map((f) => f.name).join(", ")}.
        => current;`).join("\n\n")}
}
`);
}

// --- views ------------------------------------------------------------------------------------

for (const v of ir.shared.views) {
  const derived = Object.entries(v.derived ?? {});
  emit(join(APP, "Views", `${pascal(v.label)}.cs`),
    `${banner(`${v.label} read model — fed by ${v.from.length} event type(s)`)}
using ${NS}.Contracts;

namespace ${NS}.Views;

/// <summary>
/// Context: ${v.context}. Slice: ${v.slice}.
/// Fed by: ${v.from.join(", ")}.${v.todoFor?.length ? `\n/// TODO LIST for the ${v.todoFor.join(", ")} automation: a row here is pending work.` : ""}
/// </summary>
public sealed record ${pascal(v.label)}
{
    public string Id { get; init; } = default!;

${v.fields.map((f) => {
      const d = v.derived?.[f.name];
      return `    /// <summary>${d ? `Computed from ${d.join(" + ")} — not carried by any event.` : "Carried by an upstream event."}</summary>
    public ${type(f)} ${pascal(f.name)} { get; init; }${f.nullable || CS[f.type] === "string" ? " = default!;" : ""}`;
    }).join("\n\n")}
}

// TODO(codegen): the projection. Events feeding it come from ${
      new Set(v.from.map((l) => ir.shared.events.find((e) => e.label === l)?.aggregate)).size > 1
        ? "MORE THAN ONE stream, so this is a MultiStreamProjection grouped by the identity key"
        : "a single stream, so a SingleStreamProjection or self-aggregating snapshot will do"}.
${derived.length ? `// ${derived.length} field(s) are derived and the model records their INPUTS, not the arithmetic:
${derived.map(([k, srcs]) => `//   ${k} <- ${srcs.join(" + ")}`).join("\n")}
// A human decides whether each is a sum, a count, a difference or a fold. See OPEN-QUESTIONS.md.` : ""}
`);
}

// --- validators: the periphery rules ----------------------------------------------------------

const peripheryBySlice = new Map();
for (const s of ir.slices) {
  const p = s.gwts.filter(isPeriphery);
  if (p.length && s.commands.length) peripheryBySlice.set(s, p);
}
for (const [s, gwts] of peripheryBySlice) {
  const cmd = s.commands[0];
  const agg = ir.shared.aggregates.find((a) => a.commands.some((c) => c.label === cmd));
  const fields = agg?.commands.find((c) => c.label === cmd)?.fields ?? [];
  emit(join(APP, "Slices", pascal(s.context), pascal(s.name), `${pascal(cmd)}Validator.cs`),
    `${banner(`${cmd} — periphery validation for slice "${s.name}"`)}
using FluentValidation;
using ${NS}.Slices.${pascal(s.context)}.${pascal(s.name)};

namespace ${NS}.Slices.${pascal(s.context)}.${pascal(s.name)};

/// <summary>
/// Only rules that need nothing but the request. A GWT with no GIVEN is a statement about the
/// message alone, so it can be rejected before any stream is read. Rules whose GIVEN names events
/// are decisions about accumulated state and live in the endpoint, where the aggregate is visible.
/// </summary>
public sealed class ${pascal(cmd)}Validator : AbstractValidator<${pascal(cmd)}>
{
    public ${pascal(cmd)}Validator()
    {
${gwts.map((g) => `        // ${ruleName(g)}: ${(g.rule ?? "").replace(/\s+/g, " ")}
        // TODO(codegen): RuleFor(x => x.?).Must(...).WithMessage("${ruleName(g)}");`).join("\n\n")}
    }
}

/// <summary>The command as the model declares it. Fields: ${fields.map((f) => f.name).join(", ") || "none"}.</summary>
public sealed record ${pascal(cmd)}(${params(fields)});
`);
}

// --- the Alba harness -------------------------------------------------------------------------

emit(join(TESTS, "AppFixture.cs"),
  `${banner("Alba + Testcontainers harness shared across the whole test collection")}
using Alba;
using JasperFx.CommandLine;
using Marten;
using Microsoft.Extensions.DependencyInjection;
using Testcontainers.PostgreSql;
using Wolverine;
using Xunit;

namespace ${NS}.IntegrationTests;

/// <summary>
/// One Postgres for the whole assembly, and one host. Building either per test is the difference
/// between a suite that runs in seconds and one nobody waits for.
///
/// This container is NOT the docker-compose Postgres. They must never share a connection string:
/// Marten manages schema, so a test run pointed at the demo database would drop the demo data, and
/// Testcontainers owns a lifecycle that compose would fight.
/// </summary>
public sealed class AppFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .WithDatabase("${camel(ir.system)}_tests")
        .Build();

    public IAlbaHost Host { get; private set; } = null!;

    public async Task InitializeAsync()
    {
        await _postgres.StartAsync();

        // Required when the app uses JasperFx command line integration.
        JasperFxEnvironment.AutoStartHost = true;

        Host = await AlbaHost.For<Program>(builder =>
        {
            builder.ConfigureServices(services =>
            {
                // Solo mode skips leader election and the durability agents: much faster startup.
                services.RunWolverineInSoloMode();
                // No broker in tests. Sends are still tracked, just not delivered.
                services.DisableAllExternalWolverineTransports();
            });
            builder.UseSetting("ConnectionStrings:Marten", _postgres.GetConnectionString());
        });
    }

    public async Task DisposeAsync()
    {
        await Host.StopAsync();
        await Host.DisposeAsync();
        await _postgres.DisposeAsync();
    }
}

[CollectionDefinition("integration")]
public sealed class IntegrationCollection : ICollectionFixture<AppFixture>;
`);

emit(join(TESTS, "IntegrationContext.cs"),
  `${banner("Base class for every GWT test")}
using Alba;
using Marten;
using Microsoft.Extensions.DependencyInjection;
using Wolverine.Tracking;
using Xunit;

namespace ${NS}.IntegrationTests;

[Collection("integration")]
public abstract class IntegrationContext(AppFixture fixture) : IAsyncLifetime
{
    protected IAlbaHost Host => fixture.Host;
    protected IDocumentStore Store => Host.Services.GetRequiredService<IDocumentStore>();

    /// <summary>Every test starts from an empty event store, so GIVEN means exactly what it says.</summary>
    public Task InitializeAsync() => Host.ResetAllMartenDataAsync();

    public Task DisposeAsync() => Task.CompletedTask;

    /// <summary>
    /// GIVEN: append prior events straight to the stream, bypassing the endpoints. A GWT's GIVEN is
    /// history, not a sequence of requests to replay.
    /// </summary>
    protected async Task Given(string streamKey, params object[] events)
    {
        await using var session = Store.LightweightSession();
        session.Events.Append(streamKey, events);
        await session.SaveChangesAsync();
    }

    /// <summary>THEN: the events a stream actually holds, in order.</summary>
    protected async Task<object[]> EventsFor(string streamKey)
    {
        await using var session = Store.QuerySession();
        var raw = await session.Events.FetchStreamAsync(streamKey);
        return raw.Select(x => x.Data).ToArray();
    }

    /// <summary>
    /// WHEN: an HTTP call that waits for ALL cascading Wolverine work before returning. Not an Alba
    /// extension — Alba makes the request, Wolverine.ExecuteAndWaitAsync wraps it and blocks until
    /// every message published or cascaded as a result has finished. Without the wrapper an
    /// assertion can run before the projection it is asserting on has been updated.
    /// </summary>
    protected async Task<(ITrackedSession, IScenarioResult)> WhenPosting(
        Action<Scenario> configure, int timeoutInMilliseconds = 10000)
    {
        IScenarioResult result = null!;
        var tracked = await Host.ExecuteAndWaitAsync(
            async () => { result = await Host.Scenario(configure); }, timeoutInMilliseconds);
        return (tracked, result);
    }
}
`);

// --- one test per GWT -------------------------------------------------------------------------

let gwtCount = 0;
for (const s of ir.slices) {
  if (!s.gwts.length) continue;
  const agg = ir.shared.aggregates.find((a) => a.commands.some((c) => s.commands.includes(c.label)));
  const key = agg?.identity.length ? `${pascal(agg.name)}.StreamKey(/* ${agg.identity.join(", ")} */)` : "/* stream key */";
  gwtCount += s.gwts.length;
  emit(join(TESTS, "Slices", pascal(s.context), `${pascal(s.name)}Tests.cs`),
    `${banner(`slice "${s.name}" — ${s.gwts.length} GWT(s), one test each`)}
using Alba;
using ${NS}.Aggregates;
using ${NS}.Contracts;
using Shouldly;
using Xunit;

namespace ${NS}.IntegrationTests.Slices.${pascal(s.context)};

/// <summary>
/// Generated from the model's GWT cells, NOT from the implementation — which is the only reason
/// these tests mean anything. Pattern: ${s.pattern}. Status: ${s.status}.
/// ${s.owners.length > 1 ? `This slice needs ${s.owners.join(" and ")}, so these are the contract between them.` : `Owned by ${s.owner ?? "nobody in particular"}.`}
/// </summary>
public sealed class ${pascal(s.name)}Tests(AppFixture fixture) : IntegrationContext(fixture)
{
${s.gwts.map((g, i) => {
      const thens = (g.then ?? "").split(",").map((x) => x.trim()).filter(Boolean);
      const err = thens.find((t) => /^error:/i.test(t));
      return `    // ${(g.rule || g.label || g.id).replace(/\s+/g, " ")}
    //   GIVEN ${g.given || "(nothing)"}
    //   WHEN  ${g.when || "(nothing)"}
    //   THEN  ${g.then || "(nothing)"}${isPeriphery(g) ? "\n    //   No GIVEN, so this is a periphery rule: expect 400 from the validator." : ""}
    [Fact]
    public Task ${testName(g, i)}()
        => throw new NotImplementedException(
            "TODO(codegen): ${err ? `expect a 400/ProblemDetails for ${ruleName(g)}` : `expect ${thens.join(", ") || "the modelled outcome"}`}. " +
            "Stream key: ${key.replace(/"/g, "'")}. The model gives names and types but no example data, so a human supplies the values.");`;
    }).join("\n\n")}
}
`);
}

// --- projects ---------------------------------------------------------------------------------

emit(join(APP, "Program.cs"),
  `${banner("application bootstrapping")}
using JasperFx;
using JasperFx.Resources;
using JasperFx.Events;
using Marten;
using Wolverine;
using Wolverine.FluentValidation;
using Wolverine.Http;
using Wolverine.Http.FluentValidation;
using Wolverine.Marten;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddMarten(opts =>
    {
        opts.Connection(builder.Configuration.GetConnectionString("Marten")!);
        opts.DatabaseSchemaName = "${camel(ir.system)}";

        // Every stream in this system is keyed by a composite of model fields, so stream ids are
        // strings. Marten fixes this once per store — Guid and string streams cannot be mixed.
${[...new Set(ir.shared.aggregates.filter((a) => a.identity.length).map((a) => a.identity.join(" + ")))]
      .map((k) => `        //   ${k}`).join("\n")}
        opts.Events.StreamIdentity = StreamIdentity.AsString;

        // TODO(codegen): register the projections from Views/. Which are single-stream and which
        // are multi-stream is recorded in each view file.
    })
    .IntegrateWithWolverine();

builder.Services.AddResourceSetupOnStartup();

builder.Host.UseWolverine(opts =>
{
    opts.Policies.AutoApplyTransactions();
    opts.Policies.UseDurableLocalQueues();
    opts.UseFluentValidation();
});

builder.Services.AddWolverineHttp();

var app = builder.Build();

app.MapWolverineEndpoints(opts =>
{
    // Turns a failed FluentValidation validator into a 400 with ProblemDetails.
    opts.UseFluentValidationProblemDetailMiddleware();
});

return await app.RunJasperFxCommands(args);
`);

emit(join(APP, "appsettings.json"),
  JSON.stringify({
    ConnectionStrings: { Marten: "Host=localhost;Port=5432;Database=" + camel(ir.system) + ";Username=postgres;Password=postgres" },
    Logging: { LogLevel: { Default: "Information", "Microsoft.AspNetCore": "Warning" } },
  }, null, 2) + "\n");

emit(join(APP, `${NS}.csproj`),
  `<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>${NS}</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="8.*" />
    <PackageReference Include="WolverineFx.Http" Version="5.*" />
    <PackageReference Include="WolverineFx.Http.Marten" Version="5.*" />
    <PackageReference Include="WolverineFx.Http.FluentValidation" Version="5.*" />
    <PackageReference Include="WolverineFx.Marten" Version="5.*" />
    <PackageReference Include="WolverineFx.FluentValidation" Version="5.*" />
  </ItemGroup>

</Project>
`);

emit(join(TESTS, `${NS}.IntegrationTests.csproj`),
  `<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>${NS}.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alba" Version="8.*" />
    <PackageReference Include="WolverineFx" Version="5.*" />
    <PackageReference Include="JasperFx" Version="1.*" />
    <PackageReference Include="Shouldly" Version="4.*" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\..\\src\\${NS}\\${NS}.csproj" />
  </ItemGroup>

</Project>
`);

// The XML solution format, because a classic .sln is GUID soup that no generator should emit and no
// human should diff.
emit(join(OUT, `${NS}.slnx`),
  `<Solution>
  <Project Path="src/${NS}/${NS}.csproj" />
  <Project Path="tests/${NS}.IntegrationTests/${NS}.IntegrationTests.csproj" />
</Solution>
`);

console.log(`${files.length} file(s) -> ${OUT}`);
console.log(`  ${ir.shared.events.length} event records (${owned.length} ours, ${foreign.length} foreign)`);
console.log(`  ${ir.shared.aggregates.filter((a) => a.events.length).length} aggregates, ${ir.shared.views.length} views`);
console.log(`  ${peripheryBySlice.size} validator(s) for periphery rules`);
console.log(`  ${gwtCount} GWT test(s) across ${ir.slices.filter((s) => s.gwts.length).length} slice(s)`);
console.log(`\nNOTE: Testcontainers is not in reference/llms/ — that harness is the one part written`);
console.log(`      from unverifiable knowledge. Everything else cites a mirrored page.`);
