#!/usr/bin/env node
// Generate the deterministic half of the code from the system IR.
//
//   node tools/codegen.mjs <system-dir> [--out generated/<System>]
//
// The split matters. Anything mechanically derivable from the model belongs in a SCRIPT: it is
// total, idempotent, and its diff is how a model change gets reviewed. Anything needing judgement —
// the body of a business rule, the arithmetic behind a derived field, the example data a test needs
// — belongs to the `codegen` skill, which reads reference/llms/ and fills the marked holes.
//
// So this emits: the solution, both projects, Program.cs, every event record, every aggregate's
// Create/Apply skeleton, every view type, every validator for a periphery rule, the Alba harness,
// and one test per GWT. It emits NO business logic, and says so at every hole with TODO(codegen).
//
// API shapes here are taken from reference/llms/, never from memory:
//   [WolverinePost] + [Aggregate] + [EmptyResponse]     wolverine/guide/http/marten.md
//   StreamIdentity.AsString                             marten/events/configuration.md
//   self-aggregating Create/Apply snapshots             marten/events/projections/aggregate-projections.md
//   AlbaHost.For<Program> + RunWolverineInSoloMode      wolverine/guide/http/integration-testing.md
//   UseFluentValidationProblemDetailMiddleware          wolverine/guide/http/policies.md
// Testcontainers is NOT in the mirror (zero mentions across 392 pages), so its usage is the one
// part of this file written from unverifiable knowledge. Flagged in the output.

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve, join, dirname } from "node:path";

const [target, ...rest] = process.argv.slice(2);
const flag = (n, d) => { const i = rest.indexOf(`--${n}`); return i >= 0 && rest[i + 1] ? rest[i + 1] : d; };
if (!target) {
  console.error("usage: node tools/codegen.mjs <system-dir> [--out generated/<System>]");
  process.exit(2);
}

// --- the IR is the only input -----------------------------------------------------------------

const irPath = join("build", `${resolve(target).split(/[\\/]/).pop()}.ir.json`);
execFileSync(process.execPath, [join("tools", "model.mjs"), "compile", target], { stdio: "pipe" });
const ir = JSON.parse(readFileSync(irPath, "utf8"));

const pascal = (s) => s.replace(/(^|[^a-zA-Z0-9])([a-z])/g, (_, a, b) => b.toUpperCase()).replace(/[^a-zA-Z0-9]/g, "");
const camel = (s) => { const p = pascal(s); return p[0].toLowerCase() + p.slice(1); };
const NS = pascal(ir.system);
const OUT = resolve(flag("out", join("generated", NS)));
const APP = join(OUT, "src", NS);
const TESTS = join(OUT, "tests", `${NS}.IntegrationTests`);

const CS = {                       // model type -> C# type. Anything unknown stays verbatim.
  Guid: "Guid", string: "string", decimal: "decimal", int: "int", long: "long", bool: "bool",
  DateOnly: "DateOnly", DateTimeOffset: "DateTimeOffset", DateTime: "DateTime",
};
const type = (f) => `${CS[f.type] ?? f.type}${f.nullable ? "?" : ""}`;
const params = (fields) => fields.map((f) => `${type(f)} ${pascal(f.name)}`).join(", ");

const write = (p, body) => { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, body.replace(/\n{3,}/g, "\n\n"), "utf8"); };
const banner = (what) =>
  `// <auto-generated>\n//   ${what}\n//   Generated by tools/codegen.mjs from the event model. Do not edit by hand:\n` +
  `//   re-run codegen and the change is lost. Holes marked TODO(codegen) are for the codegen skill.\n// </auto-generated>\n`;

// Where a rule is enforced. This was going to be derived from given= being empty — a rule needing no
// prior events settles from the request alone — but that fails on a real model: almost every GWT
// carries a CONTEXT given= like "the month is open", so on hour-booking the heuristic found zero
// periphery rules out of four. Declared instead, and defaulting to the safe answer (the aggregate,
// where the stream is visible). A misplaced rule in a validator cannot enforce itself.
const isPeriphery = (g) => (g.enforce ?? "aggregate") === "periphery";

// A slice nobody has started yet still gets its tests generated — they document the rules — but
// skipped, so `dotnet test` going green means the slices that ARE claimed actually pass. The skip
// count is then the honest measure of what is left.
const CLAIMED = new Set(["ready", "in-progress", "in-review", "closed"]);
const isClaimed = (s) => CLAIMED.has(s.status ?? "in-design");
const factAttr = (s) => isClaimed(s)
  ? "[Fact]"
  : `[Fact(Skip = ${JSON.stringify(`slice ${s.name} is ${s.status ?? "in-design"} — nobody has claimed these rules yet`)})]`;
const ruleName = (g) => pascal((/^error:\s*(.+)$/i.exec((g.then ?? "").trim())?.[1] ?? g.rule ?? g.id).trim());
const testName = (g, i) => {
  const base = (g.rule || g.label || g.id).replace(/\s*\n[\s\S]*$/, "");
  return pascal(base.replace(/[^a-zA-Z0-9 ]/g, " ").split(/\s+/).slice(0, 12).join(" ")) || `Rule${i + 1}`;
};

const files = [];
const kept = [];
// Fully derived: always overwritten, because the diff IS the review of a model change.
const emit = (p, body) => { write(p, body); files.push(p); };
// Needs judgement: scaffolded once, then owned by whoever filled it in. Overwriting this would
// silently delete the only part of the code a model cannot express.
const scaffold = (p, body) => {
  if (existsSync(p)) { kept.push(p); return; }
  write(p, body); files.push(p);
};

// --- events -----------------------------------------------------------------------------------

const owned = ir.shared.events.filter((e) => e.ownedBy);
const foreign = ir.shared.events.filter((e) => !e.ownedBy);
emit(join(APP, "Contracts", "Events.cs"),
  `${banner(`${ir.shared.events.length} event records — every distinct event in the system`)}
namespace ${NS}.Contracts;

${owned.map((e) => `/// <summary>${e.aggregate} stream. Produced by ${e.ownedBy}.${e.isPublic ? " Public: other contexts consume it." : ""}</summary>
public sealed record ${pascal(e.label)}(${params(e.fields)});`).join("\n\n")}

// Events we do not produce. We model the incoming contract so it can be deserialised and projected;
// nothing in this system appends them.
${foreign.map((e) => `/// <summary>External — arrives from ${e.origin}. Terminal: we have no control over it.</summary>
public sealed record ${pascal(e.label)}(${params(e.fields)});`).join("\n\n")}
`);

// --- per-slice aggregates ---------------------------------------------------------------------
//
// There is no such thing as "the" aggregate. Wolverine + Marten let every state-change slice fold
// the stream into whatever shape ITS decision needs, and live aggregation means no projection is
// registered for any of them — FetchForWriting folds on demand. So the aggregate is per SLICE, not
// per stream, which also takes it out of the shared layer and makes slices that much more
// independent.
//
// The endpoint is the decider: it receives the folded state and returns events. So a state type is
// a pure left fold and holds no rules.
//
// No Create methods. Marten will build from a no-arg constructor, and its own docs say that is
// "probably safest unless you can guarantee that a certain event type will always be first in the
// event stream" — which does not hold here: the Timesheet stream is opened by HoursBooked or by
// ZeroHoursFilled depending on whether the employee booked anything before leaving a project.

const stateName = (s) => `${pascal(s.name)}State`;
const streamOf = (s) => ir.shared.aggregates.find((a) => a.commands.some((c) => c.label === s.commands[0]));

for (const s of ir.slices) {
  if (!s.generates || !s.commands.length) continue;
  const agg = streamOf(s);
  if (!agg || !agg.events.length) continue;
  const evs = agg.events.map((l) => ir.shared.events.find((e) => e.label === l));
  const keyed = agg.identity;
  scaffold(join(APP, "Slices", pascal(s.context), pascal(s.name), `${stateName(s)}.cs`),
    `${banner(`${s.name} — the state this slice folds to make its decision`)}
using ${NS}.Contracts;

namespace ${NS}.Slices.${pascal(s.context)};

/// <summary>
/// Live aggregation over the ${agg.name} stream, keyed by ${keyed.join(" + ") || "an undeclared identity"}.
/// Nothing registers a projection for this: Marten folds it on demand when the endpoint asks.
///
/// Folds every event of the stream, not only this slice's, because a decision may depend on any of
/// them — the daily cap needs the whole month's bookings, not just the one being added.
///
/// The model draws ${evs[0].label} first in this stream, but there is deliberately no Create method:
/// a no-arg constructor lets any event open the stream.
/// </summary>
public sealed record ${stateName(s)}
{
    public string Id { get; init; } = default!;

    /// <summary>Marten's convention. The aggregate workflow uses it for optimistic concurrency.</summary>
    public int Version { get; set; }

${keyed.length ? `    public static string StreamKey(${keyed.map((k) => {
      const f = evs[0].fields.find((x) => x.name === k);
      return `${f ? type(f) : "string"} ${camel(k)}`;
    }).join(", ")})
        => $"${camel(agg.name)}:${keyed.map((k) => `{${camel(k)}}`).join(":")}";
` : ""}
${evs.map((e) => `    public static ${stateName(s)} Apply(${pascal(e.label)} e, ${stateName(s)} current)
        // TODO(codegen): fold ${pascal(e.label)} into whatever ${pascal(s.commands[0])} needs to decide.
        // Carries: ${e.fields.map((f) => f.name).join(", ")}.
        => current;`).join("\n\n")}
}
`);
}

// --- views ------------------------------------------------------------------------------------

const SYS_KEY = [...new Set(ir.shared.aggregates.flatMap((a) => a.identity))];
const registerable = [];   // views whose projection is valid enough to register inline

for (const v of ir.shared.views) {
  const derived = Object.entries(v.derived ?? {});
  const streams = [...new Set(v.from.map((l) => ir.shared.events.find((e) => e.label === l)?.aggregate).filter(Boolean))];
  const multi = streams.length > 1;
  // A row of THIS view, not of the system. Declared on the read model where the grain is known;
  // where it is not, fall back to the system key and say so, because guessing a view's grain
  // silently is how a projection ends up grouping the wrong rows together.
  const KEY = v.identity?.length ? v.identity : SYS_KEY;
  const guessedKey = !v.identity?.length;
  const sliceable = v.from.filter((l) => {
    const e = ir.shared.events.find((x) => x.label === l);
    return KEY.every((k) => e?.fields.some((f) => f.name === k));
  });
  if (!multi || sliceable.length) registerable.push(v.label);
  scaffold(join(APP, "Views", `${pascal(v.label)}.cs`),
    `${banner(`${v.label} read model — fed by ${v.from.length} event type(s)`)}
using Marten.Events.Aggregation;   // SingleStreamProjection
using Marten.Events.Projections;   // MultiStreamProjection
using ${NS}.Contracts;

namespace ${NS}.Views;

/// <summary>
/// Context: ${v.context}. Slice: ${v.slice}.
/// Fed by: ${v.from.join(", ")}.${v.todoFor?.length ? `\n/// TODO LIST for the ${v.todoFor.join(", ")} automation: a row here is pending work.` : ""}
/// </summary>
public sealed record ${pascal(v.label)}
{
    public string Id { get; init; } = default!;

${v.fields.map((f) => {
      const d = v.derived?.[f.name];
      return `    /// <summary>${d ? `Computed from ${d.join(" + ")} — not carried by any event.` : "Carried by an upstream event."}</summary>
    public ${type(f)} ${pascal(f.name)} { get; init; }${f.nullable || CS[f.type] === "string" ? " = default!;" : ""}`;
    }).join("\n\n")}
}

${derived.length ? `// ${derived.length} field(s) are derived and the model records their INPUTS, not the arithmetic:
${derived.map(([k, srcs]) => `//   ${k} <- ${srcs.join(" + ")}`).join("\n")}
// A human decides whether each is a sum, a count, a difference or a fold. See OPEN-QUESTIONS.md.
` : ""}
/// <summary>
/// ${multi ? "Multi-stream" : "Single-stream"} projection, registered INLINE in Program.cs: read models are
/// updated in the same transaction as the append, so a GWT's THEN can be asserted immediately.
/// Contrast the write side, which registers nothing and folds live.
${multi ? `///
/// Fed from ${streams.length} streams (${streams.join(", ")}), so events must be grouped explicitly.
/// Grouped by ${KEY.join(" + ")}${guessedKey ? " — GUESSED from the system key, because this read model\n/// declares no identity=. Declare it: a wrong grain groups the wrong rows together." : " (declared on the read model)"}.` : ""}
/// </summary>
public sealed class ${pascal(v.label)}Projection : ${multi
      ? `MultiStreamProjection<${pascal(v.label)}, string>`
      : `SingleStreamProjection<${pascal(v.label)}, string>`}
{
${multi ? `    public ${pascal(v.label)}Projection()
    {
${v.from.map((l) => {
        const e = ir.shared.events.find((x) => x.label === l);
        const has = KEY.every((k) => e?.fields.some((f) => f.name === k));
        return has
          ? `        Identity<${pascal(l)}>(e => $"${KEY.map((k) => `{e.${pascal(k)}}`).join(":")}");`
          : `        // TODO(codegen): ${pascal(l)} carries ${e?.fields.map((f) => f.name).join(", ") || "nothing"} —\n` +
            `        // not ${KEY.join(" + ")}, so how it groups into this view is a decision.\n` +
            `        // Identity<${pascal(l)}>(e => ...);`;
      }).join("\n")}
    }

` : ""}${v.from.map((l) => `    public static ${pascal(v.label)} Apply(${pascal(l)} e, ${pascal(v.label)} current)
        // TODO(codegen): fold ${pascal(l)} into the row.
        => current;`).join("\n\n")}
}
`);
}

// --- validators: the periphery rules ----------------------------------------------------------

const peripheryBySlice = new Map();
for (const s of ir.slices) {
  const p = s.gwts.filter(isPeriphery);
  if (p.length && s.commands.length) peripheryBySlice.set(s, p);
}
for (const [s, gwts] of peripheryBySlice) {
  const cmd = s.commands[0];
  const agg = ir.shared.aggregates.find((a) => a.commands.some((c) => c.label === cmd));
  const fields = agg?.commands.find((c) => c.label === cmd)?.fields ?? [];
  scaffold(join(APP, "Slices", pascal(s.context), pascal(s.name), `${pascal(cmd)}Validator.cs`),
    `${banner(`${cmd} — periphery validation for slice "${s.name}"`)}
using FluentValidation;
using ${NS}.Slices.${pascal(s.context)}.${pascal(s.name)};

namespace ${NS}.Slices.${pascal(s.context)}.${pascal(s.name)};

/// <summary>
/// Only rules that need nothing but the request. A GWT with no GIVEN is a statement about the
/// message alone, so it can be rejected before any stream is read. Rules whose GIVEN names events
/// are decisions about accumulated state and live in the endpoint, where the aggregate is visible.
/// </summary>
public sealed class ${pascal(cmd)}Validator : AbstractValidator<${pascal(cmd)}>
{
    public ${pascal(cmd)}Validator()
    {
${gwts.map((g) => `        // ${ruleName(g)}: ${(g.rule ?? "").replace(/\s+/g, " ")}
        // TODO(codegen): RuleFor(x => x.?).Must(...).WithMessage("${ruleName(g)}");`).join("\n\n")}
    }
}

/// <summary>The command as the model declares it. Fields: ${fields.map((f) => f.name).join(", ") || "none"}.</summary>
public sealed record ${pascal(cmd)}(${params(fields)});
`);
}

// --- the Alba harness -------------------------------------------------------------------------

emit(join(TESTS, "AppFixture.cs"),
  `${banner("Alba + Testcontainers harness shared across the whole test collection")}
using Alba;
using JasperFx.CommandLine;
using Marten;
using Marten.Schema;
using Microsoft.Extensions.DependencyInjection;
using Testcontainers.PostgreSql;
using Wolverine;
using Xunit;

namespace ${NS}.IntegrationTests;

/// <summary>
/// One Postgres for the whole assembly, and one host. Building either per test is the difference
/// between a suite that runs in seconds and one nobody waits for.
///
/// This container is NOT the docker-compose Postgres. They must never share a connection string:
/// Marten manages schema, so a test run pointed at the demo database would drop the demo data, and
/// Testcontainers owns a lifecycle that compose would fight.
/// </summary>
public sealed class AppFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .WithDatabase("${camel(ir.system)}_tests")
        .Build();

    public IAlbaHost Host { get; private set; } = null!;

    public async Task InitializeAsync()
    {
        await _postgres.StartAsync();

        // Required when the app uses JasperFx command line integration.
        JasperFxEnvironment.AutoStartHost = true;

        Host = await AlbaHost.For<Program>(builder =>
        {
            builder.ConfigureServices(services =>
            {
                // Solo mode skips leader election and the durability agents: much faster startup.
                services.RunWolverineInSoloMode();
                // No broker in tests. Sends are still tracked, just not delivered.
                services.DisableAllExternalWolverineTransports();

                // Marten attaches any IInitialData in the container to StoreOptions, and
                // ResetAllMartenDataAsync re-applies it — so every test starts in the same world.
                services.AddSingleton<IInitialData, SeedData>();
            });
            builder.UseSetting("ConnectionStrings:Marten", _postgres.GetConnectionString());
        });
    }

    public async Task DisposeAsync()
    {
        await Host.StopAsync();
        await Host.DisposeAsync();
        await _postgres.DisposeAsync();
    }
}

[CollectionDefinition("integration")]
public sealed class IntegrationCollection : ICollectionFixture<AppFixture>;
`);

// Marten's IInitialData is the answer to "a test needs example data and the model has none". The
// genesis events are seeded once with fixed ids, ResetAllData re-applies them, and every test then
// starts from the same known world instead of inventing its own.
scaffold(join(TESTS, "SeedData.cs"),
  `${banner("baseline data — one known world, re-applied before every test")}
using Marten;
using Marten.Schema;
using ${NS}.Contracts;

namespace ${NS}.IntegrationTests;

/// <summary>
/// Fixed ids so a GIVEN can name things, and so a failing test is reproducible. The model declares
/// field names and types but never example values — this is where the values live, once.
///
/// Seeds only the ${foreign.length} events nothing in this system produces (${foreign.map((e) => e.label).join(", ")}).
/// Everything else is appended by the test's own GIVEN, because that is what a GIVEN is for.
/// </summary>
public sealed class SeedData : IInitialData
{
    public static readonly Guid EmployeeId = Guid.Parse("11111111-1111-1111-1111-111111111111");
    public static readonly Guid OtherEmployeeId = Guid.Parse("22222222-2222-2222-2222-222222222222");
    public static readonly Guid ProjectId = Guid.Parse("33333333-3333-3333-3333-333333333333");
    public static readonly Guid OtherProjectId = Guid.Parse("44444444-4444-4444-4444-444444444444");
    public static readonly Guid AdminId = Guid.Parse("55555555-5555-5555-5555-555555555555");

    public const string Month = "2026-08";
    public static readonly DateOnly WorkingDay = new(2026, 8, 3);
    public static readonly DateOnly SecondWorkingDay = new(2026, 8, 4);
    public static readonly DateTimeOffset SeededAt = new(2026, 8, 1, 0, 0, 0, TimeSpan.Zero);

    public async Task Populate(IDocumentStore store, CancellationToken cancellation)
    {
        await using var session = store.LightweightSession();

        // TODO(codegen): append the foreign events above onto whatever streams the model says they
        // land in. They have origin=, not from=, so nothing here produces them — they are the world
        // this system wakes up in.

        await session.SaveChangesAsync(cancellation);
    }
}
`);

emit(join(TESTS, "IntegrationContext.cs"),
  `${banner("Base class for every GWT test")}
using Alba;
using Marten;
using Microsoft.Extensions.DependencyInjection;
using Wolverine.Tracking;
using Xunit;

namespace ${NS}.IntegrationTests;

[Collection("integration")]
public abstract class IntegrationContext(AppFixture fixture) : IAsyncLifetime
{
    protected IAlbaHost Host => fixture.Host;
    protected IDocumentStore Store => Host.Services.GetRequiredService<IDocumentStore>();

    /// <summary>Every test starts from an empty event store, so GIVEN means exactly what it says.</summary>
    public Task InitializeAsync() => Host.ResetAllMartenDataAsync();

    public Task DisposeAsync() => Task.CompletedTask;

    /// <summary>
    /// GIVEN: append prior events straight to the stream, bypassing the endpoints. A GWT's GIVEN is
    /// history, not a sequence of requests to replay.
    /// </summary>
    protected async Task Given(string streamKey, params object[] events)
    {
        await using var session = Store.LightweightSession();
        session.Events.Append(streamKey, events);
        await session.SaveChangesAsync();
    }

    /// <summary>THEN: the events a stream actually holds, in order.</summary>
    protected async Task<object[]> EventsFor(string streamKey)
    {
        await using var session = Store.QuerySession();
        var raw = await session.Events.FetchStreamAsync(streamKey);
        return raw.Select(x => x.Data).ToArray();
    }

    /// <summary>
    /// WHEN: an HTTP call that waits for ALL cascading Wolverine work before returning. Not an Alba
    /// extension — Alba makes the request, Wolverine.ExecuteAndWaitAsync wraps it and blocks until
    /// every message published or cascaded as a result has finished. Without the wrapper an
    /// assertion can run before the projection it is asserting on has been updated.
    /// </summary>
    protected async Task<(ITrackedSession, IScenarioResult)> WhenPosting(
        Action<Scenario> configure, int timeoutInMilliseconds = 10000)
    {
        IScenarioResult result = null!;
        var tracked = await Host.ExecuteAndWaitAsync(
            async () => { result = await Host.Scenario(configure); }, timeoutInMilliseconds);
        return (tracked, result);
    }
}
`);

// --- one test per GWT -------------------------------------------------------------------------

let gwtCount = 0;
for (const s of ir.slices) {
  if (!s.gwts.length) continue;
  const agg = ir.shared.aggregates.find((a) => a.commands.some((c) => s.commands.includes(c.label)));
  const key = (s.commands.length && agg?.identity.length)
    ? `${stateName(s)}.StreamKey(/* ${agg.identity.join(", ")} */)`
    : "/* no command in this slice, so no stream is written */";
  gwtCount += s.gwts.length;
  scaffold(join(TESTS, "Slices", pascal(s.context), `${pascal(s.name)}Tests.cs`),
    `${banner(`slice "${s.name}" — ${s.gwts.length} GWT(s), one test each`)}
using Alba;
using ${NS}.Contracts;
using ${NS}.Slices.${pascal(s.context)};
using Shouldly;
using Xunit;

namespace ${NS}.IntegrationTests.Slices.${pascal(s.context)};

/// <summary>
/// Generated from the model's GWT cells, NOT from the implementation — which is the only reason
/// these tests mean anything. Pattern: ${s.pattern}. Status: ${s.status}.
/// ${isClaimed(s) ? "LIVE: this slice is claimed, so every test here must pass." : "SKIPPED: promote the slice past in-design to turn these on."}
/// ${s.owners.length > 1 ? `This slice needs ${s.owners.join(" and ")}, so these are the contract between them.` : `Owned by ${s.owner ?? "nobody in particular"}.`}
/// </summary>
public sealed class ${pascal(s.name)}Tests(AppFixture fixture) : IntegrationContext(fixture)
{
${s.gwts.map((g, i) => {
      const thens = (g.then ?? "").split(",").map((x) => x.trim()).filter(Boolean);
      const err = thens.find((t) => /^error:/i.test(t));
      return `    // ${(g.rule || g.label || g.id).replace(/\s+/g, " ")}
    //   GIVEN ${g.given || "(nothing)"}
    //   WHEN  ${g.when || "(nothing)"}
    //   THEN  ${g.then || "(nothing)"}${isPeriphery(g) ? "\n    //   No GIVEN, so this is a periphery rule: expect 400 from the validator." : ""}
    ${factAttr(s)}
    public Task ${testName(g, i)}()
        => throw new NotImplementedException(
            "TODO(codegen): ${err ? `expect a 400/ProblemDetails for ${ruleName(g)}` : `expect ${thens.join(", ") || "the modelled outcome"}`}. " +
            "Stream key: ${key.replace(/"/g, "'")}. Use SeedData.EmployeeId / SeedData.Month / SeedData.ProjectId / SeedData.WorkingDay for values.");`;
    }).join("\n\n")}
}
`);
}

// --- projects ---------------------------------------------------------------------------------

emit(join(APP, "Program.cs"),
  `${banner("application bootstrapping")}
using JasperFx;
using JasperFx.Resources;
using JasperFx.Events;
using JasperFx.Events.Projections;
using Marten;
using Wolverine;
using Wolverine.FluentValidation;
using Wolverine.Http;
using Wolverine.Http.FluentValidation;
using Wolverine.Marten;
using ${NS}.Views;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddMarten(opts =>
    {
        opts.Connection(builder.Configuration.GetConnectionString("Marten")!);
        opts.DatabaseSchemaName = "${camel(ir.system)}";

        // Every stream in this system is keyed by a composite of model fields, so stream ids are
        // strings. Marten fixes this once per store — Guid and string streams cannot be mixed.
${[...new Set(ir.shared.aggregates.filter((a) => a.identity.length).map((a) => a.identity.join(" + ")))]
      .map((k) => `        //   ${k}`).join("\n")}
        opts.Events.StreamIdentity = StreamIdentity.AsString;

        // Read side: every read model is an INLINE projection, updated in the same transaction as
        // the append, so a GWT THEN can be asserted straight after the request returns.
        // Write side registers NOTHING: the per-slice state types are folded live on demand.
${ir.shared.views.map((v) => registerable.includes(v.label)
      ? `        opts.Projections.Add<${pascal(v.label)}Projection>(ProjectionLifecycle.Inline);`
      : `        // TODO(codegen): ${pascal(v.label)}Projection groups events that do not carry
        // ${SYS_KEY.join(" + ")}, so it has no slicing rule yet. Marten rejects a multi-stream
        // projection with no rules AT STARTUP, so registering it now would take the host down.
        // opts.Projections.Add<${pascal(v.label)}Projection>(ProjectionLifecycle.Inline);`
    ).join("\n")}
    })
    .IntegrateWithWolverine();

builder.Services.AddResourceSetupOnStartup();

builder.Host.UseWolverine(opts =>
{
    opts.Policies.AutoApplyTransactions();
    opts.Policies.UseDurableLocalQueues();
    opts.UseFluentValidation();
});

builder.Services.AddWolverineHttp();

var app = builder.Build();

app.MapWolverineEndpoints(opts =>
{
    // Turns a failed FluentValidation validator into a 400 with ProblemDetails.
    opts.UseFluentValidationProblemDetailMiddleware();
});

return await app.RunJasperFxCommands(args);
`);

emit(join(APP, "appsettings.json"),
  JSON.stringify({
    ConnectionStrings: { Marten: "Host=localhost;Port=5432;Database=" + camel(ir.system) + ";Username=postgres;Password=postgres" },
    Logging: { LogLevel: { Default: "Information", "Microsoft.AspNetCore": "Warning" } },
  }, null, 2) + "\n");

emit(join(APP, `${NS}.csproj`),
  `<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>${NS}</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="8.*" />
    <PackageReference Include="Marten.AspNetCore" Version="8.*" />
    <PackageReference Include="WolverineFx.Http" Version="5.*" />
    <PackageReference Include="WolverineFx.Http.Marten" Version="5.*" />
    <PackageReference Include="WolverineFx.Http.FluentValidation" Version="5.*" />
    <PackageReference Include="WolverineFx.Marten" Version="5.*" />
    <PackageReference Include="WolverineFx.FluentValidation" Version="5.*" />
  </ItemGroup>

</Project>
`);

emit(join(TESTS, `${NS}.IntegrationTests.csproj`),
  `<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>${NS}.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alba" Version="8.*" />
    <PackageReference Include="WolverineFx" Version="5.*" />
    <PackageReference Include="JasperFx" Version="1.*" />
    <PackageReference Include="Shouldly" Version="4.*" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\..\\src\\${NS}\\${NS}.csproj" />
  </ItemGroup>

</Project>
`);

// The XML solution format, because a classic .sln is GUID soup that no generator should emit and no
// human should diff.
emit(join(OUT, `${NS}.slnx`),
  `<Solution>
  <Project Path="src/${NS}/${NS}.csproj" />
  <Project Path="tests/${NS}.IntegrationTests/${NS}.IntegrationTests.csproj" />
</Solution>
`);

console.log(`${files.length} file(s) written, ${kept.length} kept (already filled in) -> ${OUT}`);
console.log(`  ${ir.shared.events.length} event records (${owned.length} ours, ${foreign.length} foreign)`);
console.log(`  ${ir.shared.aggregates.filter((a) => a.events.length).length} aggregates, ${ir.shared.views.length} views`);
console.log(`  ${peripheryBySlice.size} validator(s) for periphery rules`);
console.log(`  ${gwtCount} GWT test(s) across ${ir.slices.filter((s) => s.gwts.length).length} slice(s)`);
console.log(`\nNOTE: Testcontainers is not in reference/llms/ — that harness is the one part written`);
console.log(`      from unverifiable knowledge. Everything else cites a mirrored page.`);
