#!/usr/bin/env node
// IR -> C#. Emits a pure decider core plus given/when/then tests, per slice.
//
//   node tools/gen-csharp.mjs <model.json> [--out generated]
//
// Deliberately infrastructure-free: Decide(state, cmd, now) -> events and Evolve(state, evt)
// -> state are plain functions, so the generated tests run under `dotnet test` with no
// Postgres and no Marten. Marten wiring is a separate layer that calls into this core.
//
// Nothing here is hand-editable. Change the diagram, re-run, re-read the diff.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, join } from "node:path";

const pascal = (s) => s.replace(/(^|[^A-Za-z0-9])([a-z])/g, (_, p, c) => c.toUpperCase()).replace(/[^A-Za-z0-9]/g, "");
const camel = (s) => s.charAt(0).toLowerCase() + s.slice(1);

// A deterministic valid value per type, so the happy-path test needs no hand-written fixture.
// Examples in the model override these to produce violating inputs.
function sampleValue(field, nowExpr) {
  switch (field.type) {
    case "Guid": return `Guid.Parse("00000000-0000-0000-0000-0000000000{ID}")`;
    case "decimal": return "100m";
    case "double": return "100d";
    case "int": case "long": return "1";
    case "bool": return "true";
    case "DateTimeOffset": case "DateTime": return nowExpr;
    default: return `"sample-${field.name}"`;
  }
}

function literal(field, raw) {
  // A modeller writes plain values in examples=; C# needs suffixes and quotes.
  if (raw === undefined) return null;
  switch (field.type) {
    case "decimal": return `${raw}m`;
    case "double": return `${raw}d`;
    case "int": case "long": case "bool": return raw;
    case "Guid": return `Guid.Parse("${raw}")`;
    default: return `"${raw}"`;
  }
}

const header = (ir) => `// <auto-generated />
// Generated by tools/gen-csharp.mjs from ${ir.source}
// Page: "${ir.page}". Do not edit — change the diagram and regenerate.
#nullable enable
`;

function csType(f) {
  return f.nullable ? `${f.type}?` : f.type;
}

function recordFor(name, fields) {
  const params = fields.map((f) => `${csType(f)} ${pascal(f.name)}`).join(", ");
  return `public sealed record ${name}(${params});`;
}

function generate(ir) {
  const files = [];
  const aggregates = [...new Set(ir.slices.map((s) => s.aggregate).filter(Boolean))];

  files.push({
    path: "Domain/Rejection.cs",
    body: `${header(ir)}
namespace EventModel.Domain;

/// Thrown when a command violates a rule declared on the diagram (rejects=).
public sealed class RejectionException : Exception
{
    public string Rule { get; }

    public RejectionException(string rule, string condition)
        : base($"{rule}: command rejected because {condition}")
        => Rule = rule;
}
`,
  });

  for (const agg of aggregates) {
    const slices = ir.slices.filter((s) => s.aggregate === agg);
    const events = slices.flatMap((s) => s.events);
    const commands = slices.flatMap((s) => s.commands);

    // State is the fold of every event payload this aggregate emits. Field names repeated
    // across events collapse to one property — last event wins, which is what a fold does.
    const stateFields = [];
    for (const ev of events) {
      for (const f of ev.fields) {
        if (!stateFields.some((x) => x.name === f.name)) stateFields.push(f);
      }
    }

    files.push({
      path: `Domain/${agg}/${agg}Events.cs`,
      body: `${header(ir)}
namespace EventModel.Domain.${agg}Aggregate;

${events.map((ev) => recordFor(ev.label, ev.fields)).join("\n")}
`,
    });

    files.push({
      path: `Domain/${agg}/${agg}Commands.cs`,
      body: `${header(ir)}
namespace EventModel.Domain.${agg}Aggregate;

${commands.map((c) => recordFor(c.label, c.fields)).join("\n")}
`,
    });

    files.push({
      path: `Domain/${agg}/${agg}State.cs`,
      body: `${header(ir)}
namespace EventModel.Domain.${agg}Aggregate;

/// The fold of this aggregate's events. Exists=false means the stream is empty.
public sealed record ${agg}State(
    bool Exists${stateFields.length ? "," : ""}
${stateFields.map((f) => `    ${f.type}? ${pascal(f.name)}`).join(",\n")}
)
{
    public static readonly ${agg}State Initial = new(false${stateFields.map(() => ", null").join("")});

    public ${agg}State Evolve(object @event) => @event switch
    {
${events
  .map(
    (ev) =>
      `        ${ev.label} e => this with { Exists = true${ev.fields
        .map((f) => `, ${pascal(f.name)} = e.${pascal(f.name)}`)
        .join("")} },`
  )
  .join("\n")}
        _ => this,
    };

    public static ${agg}State From(IEnumerable<object> history)
    {
        var state = Initial;
        foreach (var e in history) state = state.Evolve(e);
        return state;
    }
}
`,
    });

    // One Decide overload per command. Guards first, then the event.
    const deciders = commands.map((c) => {
      const ev = events.find((e) => c.emits.includes(e.label));
      const guards = c.rejects
        .map(
          (r) =>
            `        if (${r.condition.replace(/\b([a-z][A-Za-z0-9]*)\b/g, (m) =>
              c.fields.some((f) => f.name === m) ? `command.${pascal(m)}` : m
            )})\n            throw new RejectionException("${r.name}", "${r.condition.replace(/"/g, '\\"')}");`
        )
        .join("\n\n");
      const args = ev.fields
        .map((f) => {
          const fromCmd = c.fields.find((cf) => cf.name === f.name);
          return `                ${pascal(f.name)}: ${fromCmd ? `command.${pascal(f.name)}` : "now"}`;
        })
        .join(",\n");
      return `    /// Slice: ${c.id.replace(/^cmd-/, "")} — ${c.label} emits ${c.emits.join(", ")}.
    public static IReadOnlyList<object> Decide(${agg}State state, ${c.label} command, DateTimeOffset now)
    {
${guards || "        // no rules declared on the diagram"}

        return new object[]
        {
            new ${ev.label}(
${args}),
        };
    }`;
    });

    files.push({
      path: `Domain/${agg}/${agg}Decider.cs`,
      body: `${header(ir)}
using EventModel.Domain;

namespace EventModel.Domain.${agg}Aggregate;

/// Pure decision functions. No I/O, no framework — the whole point.
public static class ${agg}Decider
{
${deciders.join("\n\n")}
}
`,
    });

    // --- tests: one class per slice, given/when/then ---
    for (const s of slices) {
      const tests = [];
      for (const c of s.commands) {
        const ev = events.find((e) => c.emits.includes(e.label));
        const nowExpr = "Now";
        // Counter resets per command build, so the same field gets the same literal in
        // every test of this slice — a drifting Guid reads like a bug in the generator.
        const build = (overrides = {}) => {
          let guidSeq = 1;
          return c.fields
            .map((f) => {
              const over = literal(f, overrides[f.name]);
              const val = over ?? sampleValue(f, nowExpr).replace("{ID}", String(guidSeq++).padStart(2, "0"));
              return `            ${pascal(f.name)}: ${val}`;
            })
            .join(",\n");
        };

        tests.push(`    [Fact]
    public void Given_no_history_When_${c.label}_Then_${ev.label}()
    {
        var state = ${agg}State.From(Array.Empty<object>());
        var command = new ${c.label}(
${build()});

        var events = ${agg}Decider.Decide(state, command, Now);

        var e = Assert.IsType<${ev.label}>(Assert.Single(events));
${ev.fields
  .map((f) => {
    const fromCmd = c.fields.find((cf) => cf.name === f.name);
    return `        Assert.Equal(${fromCmd ? `command.${pascal(f.name)}` : "Now"}, e.${pascal(f.name)});`;
  })
  .join("\n")}
    }`);

        for (const r of c.rejects) {
          tests.push(`    [Fact]
    public void Given_no_history_When_${c.label}_violates_${r.name}_Then_rejected()
    {
        var state = ${agg}State.From(Array.Empty<object>());
        var command = new ${c.label}(
${build(c.examples?.[r.name] ?? {})});

        var ex = Assert.Throws<RejectionException>(() => ${agg}Decider.Decide(state, command, Now));

        Assert.Equal("${r.name}", ex.Rule);
    }`);
        }

        tests.push(`    [Fact]
    public void ${ev.label}_folds_into_state()
    {
        var state = ${agg}State.From(Array.Empty<object>());
        var command = new ${c.label}(
${build()});

        var next = ${agg}State.From(${agg}Decider.Decide(state, command, Now));

        Assert.True(next.Exists);
    }`);
      }

      files.push({
        path: `Domain.Tests/${pascal(s.name)}SliceTests.cs`,
        body: `${header(ir)}
using EventModel.Domain;
using EventModel.Domain.${agg}Aggregate;
using Xunit;

namespace EventModel.Domain.Tests;

/// Slice "${s.name}" (${s.kind}): ${s.wireframes.map((w) => w.label).join(", ") || "no wireframe"} -> ${s.commands.map((c) => c.label).join(", ")} -> ${s.events.map((e) => e.label).join(", ")}
public class ${pascal(s.name)}SliceTests
{
    private static readonly DateTimeOffset Now = new(2026, 8, 4, 12, 0, 0, TimeSpan.Zero);

${tests.join("\n\n")}
}
`,
      });
    }
  }

  return files;
}

const [target, ...rest] = process.argv.slice(2);
if (!target) {
  console.error("usage: node tools/gen-csharp.mjs <model.json> [--out generated]");
  process.exit(2);
}
const outIdx = rest.indexOf("--out");
const outDir = resolve(outIdx >= 0 && rest[outIdx + 1] ? rest[outIdx + 1] : "generated");
const ir = JSON.parse(readFileSync(resolve(target), "utf8").replace(/^﻿/, ""));

const files = generate(ir);
for (const f of files) {
  const full = join(outDir, f.path);
  mkdirSync(join(full, ".."), { recursive: true });
  writeFileSync(full, f.body.replace(/\r?\n/g, "\r\n"), "utf8");
  console.log(`  ${f.path}`);
}
console.log(`\n${files.length} file(s) from ${ir.slices.length} slice(s)`);
