#!/usr/bin/env node
// Measure the distance between the reference implementations and the generator that reads them.
//
//   node tools/refimpl.mjs drift [--folder <name>]
//
// WHY THIS EXISTS. KIT-FINDINGS BP12: regenerating all six folders for an unrelated reason produced diffs
// that had nothing to do with the change being made — six Dockerfiles a citation behind, and an ingest
// scaffold one folder had never received. These are the worked examples CLAUDE.md tells every agent to read,
// they contain `emit` files by construction, and nothing measured whether they were current.
//
// AND "NOTHING MEASURES THE DISTANCE" IS TWO PROBLEMS WEARING ONE NAME. Only one of them is mechanical:
//
//   emit drift        an `emit` file differing from what the generator now produces. Total and idempotent by
//                     definition, so any difference IS the finding and no judgement is involved. THIS TOOL.
//   editorial decay   a stale `scaffold`, prose that has gone false, a measured claim the libraries have
//                     invalidated. Needs a reader. NOT THIS TOOL, and shipping this must not imply otherwise.
//
// CLAUDE.md deferred BOTH to "a future skill or agent", and that is why the mechanical half went unmeasured
// for months: the half that needed a person kept the half that did not from being built.
//
// HOW. Regenerate each folder into a THROWAWAY directory and compare only the emit files. Nothing is written
// into the folders, so this cannot break one — which is what makes it cheap enough to run every time.

import { readFileSync, readdirSync, existsSync, mkdtempSync, rmSync, statSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const KIT = fileURLToPath(new URL("..", import.meta.url)).replace(/[\\/]$/, "");
const REFS = join(KIT, "reference-implementations");
const args = process.argv.slice(2);
const cmd = args[0];
const flag = (n) => { const i = args.indexOf(`--${n}`); return i >= 0 && args[i + 1] && !args[i + 1].startsWith("--") ? args[i + 1] : null; };

if (cmd !== "drift") {
  console.error("usage:\n  node tools/refimpl.mjs drift [--folder <name>]\n\n" +
    "  Regenerates each reference implementation into a throwaway directory and diffs the EMIT files\n" +
    "  against the committed ones. It writes nothing into the folders.");
  process.exit(2);
}

// Each folder holds exactly one model directory: the one that is not build/ or generated/.
const folders = readdirSync(REFS, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .filter((n) => !flag("folder") || n === flag("folder"))
  .map((name) => {
    const dir = join(REFS, name);
    const model = readdirSync(dir, { withFileTypes: true })
      .filter((e) => e.isDirectory() && !["build", "generated"].includes(e.name))
      .map((e) => e.name)[0];
    return { name, dir, model, generated: join(dir, "generated") };
  })
  .filter((f) => f.model && existsSync(f.generated));

if (!folders.length) { console.error(`no reference implementation found${flag("folder") ? ` named ${flag("folder")}` : ""}.`); process.exit(1); }

const walk = (root) => {
  const out = [];
  (function rec(d) {
    if (!existsSync(d)) return;
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) { if (!/^(bin|obj|node_modules)$/.test(e.name)) rec(p); }
      else out.push(relative(root, p).replace(/\\/g, "/"));
    }
  })(root);
  return out.sort();
};

// A SCAFFOLD IS HAND-OWNED FROM THE MOMENT IT EXISTS, so it is not drift and must not be diffed. The
// generator stamps the distinction itself, so read it off the FRESH output rather than keeping a list here
// that could disagree with codegen.mjs.
const isScaffold = (text) => text.includes("<auto-generated-scaffold>");
// Line endings are not drift: every file in this repo is CRLF on disk and the generator writes LF.
const norm = (s) => s.replace(/\r\n/g, "\n").replace(/\s+$/, "");

let totalDrift = 0;
const summary = [];

for (const f of folders) {
  const tmp = mkdtempSync(join(tmpdir(), "refimpl-"));
  let ok = true;
  try {
    execFileSync(process.execPath,
      [join(KIT, "tools", "codegen.mjs"), join(f.dir, f.model), "--project", tmp, "--out", "generated"],
      { encoding: "utf8", maxBuffer: 1 << 28, stdio: ["ignore", "pipe", "pipe"] });
  } catch (e) {
    // LOUD. A folder that cannot be regenerated is the strongest possible drift finding, and swallowing it
    // would be the exact failure this whole family of findings is about.
    console.log(`\n${f.name}\n  CANNOT REGENERATE — this is drift of the worst kind, not a clean result:`);
    console.log(`    ${(e.stderr || e.message || String(e)).toString().trim().split("\n")[0]}`);
    summary.push({ name: f.name, broken: true });
    totalDrift++; ok = false;
  }
  if (!ok) { rmSync(tmp, { recursive: true, force: true }); continue; }

  const fresh = join(tmp, "generated");
  const differs = [], missing = [], orphaned = [];
  // COUNTED AND PRINTED, so "up to date" is a quantified claim rather than a bare one. A comparison of zero
  // files would also print "up to date", and that is precisely the vacuous result CLAUDE.md's standing rule
  // is about: state how many files the clean answer rests on.
  let compared = 0, skipped = 0;

  for (const rel of walk(fresh)) {
    const a = readFileSync(join(fresh, rel), "utf8");
    if (isScaffold(a)) { skipped++; continue; }         // hand-owned; the generator only ever wrote the stub
    compared++;
    const committed = join(f.generated, rel);
    if (!existsSync(committed)) { missing.push(rel); continue; }
    if (norm(a) !== norm(readFileSync(committed, "utf8"))) differs.push(rel);
  }
  // An emit-bannered file the generator NO LONGER produces: emitted by an older version, now orphaned.
  //
  // SCOPED TO DIRECTORIES CODEGEN ITSELF WRITES INTO, because a generated tree has MORE THAN ONE GENERATOR
  // and the first version of this check did not know that. `architect.mjs tests` writes
  // `tests/<Sys>.IntegrationTests/Concurrency/` — the race tests and `ConcurrencyHarness.cs` — with the same
  // emit banner, so every folder with race tests was reported as orphaned on the first run. That was the
  // tool being wrong, not the folder.
  //
  // Not fixed by also running `architect tests` into the throwaway: it would then report reservation's three
  // UNWRITTEN race tests as MISSING, which is architect's own finding and belongs in its own report, not
  // relabelled as drift. Two reports, two owners.
  const freshSet = new Set(walk(fresh));
  const freshDirs = new Set([...freshSet].map((r) => dirname(r)));
  for (const rel of walk(f.generated)) {
    if (freshSet.has(rel)) continue;
    if (!freshDirs.has(dirname(rel))) continue;        // a directory codegen does not own — another tool's
    const p = join(f.generated, rel);
    if (!/\.(cs|csproj|slnx|json|yml|conf)$/.test(rel) && !/Dockerfile$/.test(rel)) continue;
    const text = readFileSync(p, "utf8");
    if (text.includes("<auto-generated>") && !isScaffold(text)) orphaned.push(rel);
  }

  const n = differs.length + missing.length + orphaned.length;
  totalDrift += n;
  summary.push({ name: f.name, differs: differs.length, missing: missing.length, orphaned: orphaned.length, compared, skipped });

  console.log(`\n${f.name}   ${compared} emit file(s) compared, ${skipped} scaffold(s) skipped${n === 0 ? "   — up to date" : ""}`);
  for (const r of differs)  console.log(`  DIFFERS   ${r}`);
  for (const r of missing)  console.log(`  MISSING   ${r}   (the generator emits this and the folder has never received it)`);
  for (const r of orphaned) console.log(`  ORPHANED  ${r}   (emit-bannered, and the generator no longer produces it)`);

  rmSync(tmp, { recursive: true, force: true });
}

console.log(`\n${"=".repeat(96)}`);
for (const s of summary) {
  console.log(s.broken
    ? `  ${s.name.padEnd(28)} CANNOT REGENERATE`
    : `  ${s.name.padEnd(28)} ${s.differs} differ, ${s.missing} missing, ${s.orphaned} orphaned`);
}
const comparedAll = summary.reduce((a, s) => a + (s.compared ?? 0), 0);
console.log(totalDrift === 0
  ? `\nNo emit drift across ${comparedAll} emit file(s) in ${folders.length} folder(s). Regenerating them would change nothing.`
  : `\n${totalDrift} emit file(s) adrift. Fix by regenerating the folder — the command is in its README:\n` +
    `  node tools/codegen.mjs reference-implementations/<f>/<model> --project reference-implementations/<f> --out generated`);

// WHAT THIS CANNOT SEE, printed every time and not only on a failure, because a green run here is exactly
// when somebody is most likely to conclude the folders are current.
console.log(`
IT ONLY SEES EMIT. A clean run above means the mechanically derivable half is current. It says NOTHING about:
  * a stale SCAFFOLD — and that is where all the reasoning lives. Every worked comparison in these folders
    (four wakeup mechanisms, six read recipes, four concurrency arms) sits in scaffolded files or a README,
    and a generator improvement never reaches those. This tool cannot tell "deliberately different" from
    "left behind".
  * PROSE THAT HAS GONE FALSE. \`automation/\` had no README at all while CLAUDE.md cited it four times as
    the thing to read; no diff of emit output would ever have said so.
  * A FOLDER THAT NO LONGER DEMONSTRATES WHAT IT CLAIMS. The translation ingest seam was correct emit output
    the whole time — what was wrong was that the folder and the generator disagreed about which class is the
    seam, and only reading the model's automations= showed it.
  * WHETHER THE MEASURED CLAIMS ARE STILL TRUE. "1m0s -> 47s", "22/22 call sites", "restore resolved Marten
    2.10.3" are these folders' real value, and they decay silently as the libraries move.
Those need a reader. Do not report "drift: clean" as "the reference implementations are current".`);

process.exit(totalDrift === 0 ? 0 : 1);
